"""add_company_logo_url

Revision ID: 04a8f746b8f2
Revises: f21ced20f061
Create Date: 2026-03-07 15:10:54.823426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04a8f746b8f2'
down_revision: Union[str, Sequence[str], None] = 'f21ced20f061'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('logo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'logo_url')
    # ### end Alembic commands ###
