"""Add vendedor_id to sales_budgets

Revision ID: 07761b74db46
Revises: 405ead5d4919
Create Date: 2026-03-24 11:31:20.960118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07761b74db46'
down_revision: Union[str, Sequence[str], None] = '405ead5d4919'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_budgets', sa.Column('vendedor_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_sales_budgets_vendedor_id'), 'sales_budgets', ['vendedor_id'], unique=False)
    op.create_foreign_key(None, 'sales_budgets', 'professionals', ['vendedor_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales_budgets', type_='foreignkey')
    op.drop_index(op.f('ix_sales_budgets_vendedor_id'), table_name='sales_budgets')
    op.drop_column('sales_budgets', 'vendedor_id')
    # ### end Alembic commands ###
