"""add_sales_budgets_module

Revision ID: 0ccb8ee54fa0
Revises: 33edfc400bac
Create Date: 2026-03-16 19:55:26.915537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ccb8ee54fa0'
down_revision: Union[str, Sequence[str], None] = '33edfc400bac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_budgets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('numero_orcamento', sa.String(length=50), nullable=True),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('data_orcamento', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('markup_padrao', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('perc_despesa_adm', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('perc_comissao', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('perc_frete_venda', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('perc_pis', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('perc_cofins', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('perc_csll', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('perc_irpj', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('perc_iss', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('perc_icms_interno', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('perc_icms_externo', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_budgets_company_id'), 'sales_budgets', ['company_id'], unique=False)
    op.create_index(op.f('ix_sales_budgets_customer_id'), 'sales_budgets', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sales_budgets_tenant_id'), 'sales_budgets', ['tenant_id'], unique=False)
    op.create_table('sales_budget_responsaveis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('budget_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['sales_budgets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_budget_responsaveis_budget_id'), 'sales_budget_responsaveis', ['budget_id'], unique=False)
    op.create_index(op.f('ix_sales_budget_responsaveis_user_id'), 'sales_budget_responsaveis', ['user_id'], unique=False)
    op.create_table('sales_budget_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('budget_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('tipo_item', sa.String(length=30), nullable=False),
    sa.Column('descricao_servico', sa.String(length=255), nullable=True),
    sa.Column('usa_parametros_padrao', sa.Boolean(), nullable=False),
    sa.Column('custo_unit_base', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('markup', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('venda_unit', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('perc_frete_venda', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('frete_venda_unit', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('perc_pis', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('pis_unit', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('perc_cofins', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('cofins_unit', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('perc_csll', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('csll_unit', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('perc_irpj', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('irpj_unit', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('perc_icms', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('icms_unit', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('tem_st', sa.Boolean(), nullable=False),
    sa.Column('perc_iss', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('iss_unit', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('perc_despesa_adm', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('despesa_adm_unit', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('perc_comissao', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('comissao_unit', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('lucro_unit', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('margem_unit', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('total_venda', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['sales_budgets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_budget_items_budget_id'), 'sales_budget_items', ['budget_id'], unique=False)
    op.create_index(op.f('ix_sales_budget_items_product_id'), 'sales_budget_items', ['product_id'], unique=False)
    op.add_column('company_sales_parameters', sa.Column('frete_venda_padrao', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_sales_parameters', 'frete_venda_padrao')
    op.drop_index(op.f('ix_sales_budget_items_product_id'), table_name='sales_budget_items')
    op.drop_index(op.f('ix_sales_budget_items_budget_id'), table_name='sales_budget_items')
    op.drop_table('sales_budget_items')
    op.drop_index(op.f('ix_sales_budget_responsaveis_user_id'), table_name='sales_budget_responsaveis')
    op.drop_index(op.f('ix_sales_budget_responsaveis_budget_id'), table_name='sales_budget_responsaveis')
    op.drop_table('sales_budget_responsaveis')
    op.drop_index(op.f('ix_sales_budgets_tenant_id'), table_name='sales_budgets')
    op.drop_index(op.f('ix_sales_budgets_customer_id'), table_name='sales_budgets')
    op.drop_index(op.f('ix_sales_budgets_company_id'), table_name='sales_budgets')
    op.drop_table('sales_budgets')
    # ### end Alembic commands ###
