"""add_checklist_and_tasks

Revision ID: 1023f9448fcb
Revises: 401accd6f92a
Create Date: 2026-06-17 08:53:11.358369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1023f9448fcb'
down_revision: Union[str, Sequence[str], None] = '401accd6f92a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('licitacao_checklist_grupos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('licitacao_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['licitacao_id'], ['licitacoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licitacao_checklist_grupos_licitacao_id'), 'licitacao_checklist_grupos', ['licitacao_id'], unique=False)
    op.create_index(op.f('ix_licitacao_checklist_grupos_tenant_id'), 'licitacao_checklist_grupos', ['tenant_id'], unique=False)
    op.create_table('licitacao_checklist_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('grupo_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('usuario_id', sa.String(), nullable=True),
    sa.Column('data_conclusao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['licitacao_checklist_grupos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licitacao_checklist_items_grupo_id'), 'licitacao_checklist_items', ['grupo_id'], unique=False)
    op.create_index(op.f('ix_licitacao_checklist_items_tenant_id'), 'licitacao_checklist_items', ['tenant_id'], unique=False)
    op.create_table('licitacao_checklist_aplicacoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('licitacao_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('data_conclusao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['licitacao_checklist_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['licitacao_id'], ['licitacoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licitacao_checklist_aplicacoes_item_id'), 'licitacao_checklist_aplicacoes', ['item_id'], unique=False)
    op.create_index(op.f('ix_licitacao_checklist_aplicacoes_licitacao_id'), 'licitacao_checklist_aplicacoes', ['licitacao_id'], unique=False)
    op.create_index(op.f('ix_licitacao_checklist_aplicacoes_tenant_id'), 'licitacao_checklist_aplicacoes', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_licitacao_checklist_aplicacoes_usuario_id'), 'licitacao_checklist_aplicacoes', ['usuario_id'], unique=False)
    op.create_table('licitacao_tarefas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('licitacao_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('checklist_item_id', sa.UUID(), nullable=True),
    sa.Column('checklist_aplicacao_id', sa.UUID(), nullable=True),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('responsavel_id', sa.String(), nullable=False),
    sa.Column('criador_id', sa.String(), nullable=False),
    sa.Column('data_limite', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['checklist_aplicacao_id'], ['licitacao_checklist_aplicacoes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['checklist_item_id'], ['licitacao_checklist_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['criador_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['licitacao_id'], ['licitacoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responsavel_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licitacao_tarefas_licitacao_id'), 'licitacao_tarefas', ['licitacao_id'], unique=False)
    op.create_index(op.f('ix_licitacao_tarefas_responsavel_id'), 'licitacao_tarefas', ['responsavel_id'], unique=False)
    op.create_index(op.f('ix_licitacao_tarefas_tenant_id'), 'licitacao_tarefas', ['tenant_id'], unique=False)
    op.create_table('licitacao_tarefa_andamentos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tarefa_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.String(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('status_anterior', sa.String(length=50), nullable=False),
    sa.Column('status_novo', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tarefa_id'], ['licitacao_tarefas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licitacao_tarefa_andamentos_tarefa_id'), 'licitacao_tarefa_andamentos', ['tarefa_id'], unique=False)
    op.create_index(op.f('ix_licitacao_tarefa_andamentos_tenant_id'), 'licitacao_tarefa_andamentos', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_licitacao_tarefa_andamentos_tenant_id'), table_name='licitacao_tarefa_andamentos')
    op.drop_index(op.f('ix_licitacao_tarefa_andamentos_tarefa_id'), table_name='licitacao_tarefa_andamentos')
    op.drop_table('licitacao_tarefa_andamentos')
    op.drop_index(op.f('ix_licitacao_tarefas_tenant_id'), table_name='licitacao_tarefas')
    op.drop_index(op.f('ix_licitacao_tarefas_responsavel_id'), table_name='licitacao_tarefas')
    op.drop_index(op.f('ix_licitacao_tarefas_licitacao_id'), table_name='licitacao_tarefas')
    op.drop_table('licitacao_tarefas')
    op.drop_index(op.f('ix_licitacao_checklist_aplicacoes_usuario_id'), table_name='licitacao_checklist_aplicacoes')
    op.drop_index(op.f('ix_licitacao_checklist_aplicacoes_tenant_id'), table_name='licitacao_checklist_aplicacoes')
    op.drop_index(op.f('ix_licitacao_checklist_aplicacoes_licitacao_id'), table_name='licitacao_checklist_aplicacoes')
    op.drop_index(op.f('ix_licitacao_checklist_aplicacoes_item_id'), table_name='licitacao_checklist_aplicacoes')
    op.drop_table('licitacao_checklist_aplicacoes')
    op.drop_index(op.f('ix_licitacao_checklist_items_tenant_id'), table_name='licitacao_checklist_items')
    op.drop_index(op.f('ix_licitacao_checklist_items_grupo_id'), table_name='licitacao_checklist_items')
    op.drop_table('licitacao_checklist_items')
    op.drop_index(op.f('ix_licitacao_checklist_grupos_tenant_id'), table_name='licitacao_checklist_grupos')
    op.drop_index(op.f('ix_licitacao_checklist_grupos_licitacao_id'), table_name='licitacao_checklist_grupos')
    op.drop_table('licitacao_checklist_grupos')
    # ### end Alembic commands ###
