"""Add purchase budgets module

Revision ID: 10a1c52fa98e
Revises: ac7a3f695c3d
Create Date: 2026-03-14 08:27:52.777117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10a1c52fa98e'
down_revision: Union[str, Sequence[str], None] = 'ac7a3f695c3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_conditions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=False),
    sa.Column('prazo', sa.Integer(), nullable=False),
    sa.Column('parcelas', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_conditions_tenant_id'), 'payment_conditions', ['tenant_id'], unique=False)
    op.create_table('purchase_budgets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.String(), nullable=False),
    sa.Column('payment_condition_id', sa.UUID(), nullable=True),
    sa.Column('data_orcamento', sa.DateTime(timezone=True), nullable=False),
    sa.Column('validade', sa.DateTime(timezone=True), nullable=True),
    sa.Column('vendedor_nome', sa.String(length=100), nullable=True),
    sa.Column('vendedor_telefone', sa.String(length=50), nullable=True),
    sa.Column('vendedor_email', sa.String(length=100), nullable=True),
    sa.Column('tipo_orcamento', sa.String(length=50), nullable=False),
    sa.Column('frete_tipo', sa.String(length=10), nullable=False),
    sa.Column('frete_percent', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('ipi_calculado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_condition_id'], ['payment_conditions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_budgets_company_id'), 'purchase_budgets', ['company_id'], unique=False)
    op.create_index(op.f('ix_purchase_budgets_supplier_id'), 'purchase_budgets', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_purchase_budgets_tenant_id'), 'purchase_budgets', ['tenant_id'], unique=False)
    op.create_table('purchase_budget_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('budget_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('codigo_fornecedor', sa.String(length=100), nullable=True),
    sa.Column('ncm', sa.String(length=20), nullable=True),
    sa.Column('valor_unitario', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('frete_percent', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('frete_valor', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('ipi_percent', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('ipi_valor', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('icms_percent', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('total_item', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['purchase_budgets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_budget_items_budget_id'), 'purchase_budget_items', ['budget_id'], unique=False)
    op.create_index(op.f('ix_purchase_budget_items_product_id'), 'purchase_budget_items', ['product_id'], unique=False)
    op.create_table('purchase_budget_negotiations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('budget_id', sa.UUID(), nullable=False),
    sa.Column('data_negociacao', sa.DateTime(timezone=True), nullable=False),
    sa.Column('desconto_percent', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['purchase_budgets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_budget_negotiations_budget_id'), 'purchase_budget_negotiations', ['budget_id'], unique=False)
    op.create_table('purchase_budget_negotiation_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('negotiation_id', sa.UUID(), nullable=False),
    sa.Column('budget_item_id', sa.UUID(), nullable=False),
    sa.Column('valor_original', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('desconto_percent', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('valor_final', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['budget_item_id'], ['purchase_budget_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['negotiation_id'], ['purchase_budget_negotiations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_budget_negotiation_items_budget_item_id'), 'purchase_budget_negotiation_items', ['budget_item_id'], unique=False)
    op.create_index(op.f('ix_purchase_budget_negotiation_items_negotiation_id'), 'purchase_budget_negotiation_items', ['negotiation_id'], unique=False)
    op.add_column('products', sa.Column('ultimo_preco_compra', sa.Numeric(precision=15, scale=4), nullable=True))
    op.add_column('products', sa.Column('data_ultimo_preco', sa.DateTime(timezone=True), nullable=True))
    op.add_column('products', sa.Column('fornecedor_ultimo_preco_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'products', 'suppliers', ['fornecedor_ultimo_preco_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'fornecedor_ultimo_preco_id')
    op.drop_column('products', 'data_ultimo_preco')
    op.drop_column('products', 'ultimo_preco_compra')
    op.drop_index(op.f('ix_purchase_budget_negotiation_items_negotiation_id'), table_name='purchase_budget_negotiation_items')
    op.drop_index(op.f('ix_purchase_budget_negotiation_items_budget_item_id'), table_name='purchase_budget_negotiation_items')
    op.drop_table('purchase_budget_negotiation_items')
    op.drop_index(op.f('ix_purchase_budget_negotiations_budget_id'), table_name='purchase_budget_negotiations')
    op.drop_table('purchase_budget_negotiations')
    op.drop_index(op.f('ix_purchase_budget_items_product_id'), table_name='purchase_budget_items')
    op.drop_index(op.f('ix_purchase_budget_items_budget_id'), table_name='purchase_budget_items')
    op.drop_table('purchase_budget_items')
    op.drop_index(op.f('ix_purchase_budgets_tenant_id'), table_name='purchase_budgets')
    op.drop_index(op.f('ix_purchase_budgets_supplier_id'), table_name='purchase_budgets')
    op.drop_index(op.f('ix_purchase_budgets_company_id'), table_name='purchase_budgets')
    op.drop_table('purchase_budgets')
    op.drop_index(op.f('ix_payment_conditions_tenant_id'), table_name='payment_conditions')
    op.drop_table('payment_conditions')
    # ### end Alembic commands ###
