"""Add own_services to opportunity_kit_items

Revision ID: 158c82263f5e
Revises: 0eec3af19026
Create Date: 2026-04-01 19:48:44.423012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '158c82263f5e'
down_revision: Union[str, Sequence[str], None] = '0eec3af19026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunity_kit_items', sa.Column('tipo_item', sa.String(length=50), nullable=False))
    op.add_column('opportunity_kit_items', sa.Column('own_service_id', sa.UUID(), nullable=True))
    op.alter_column('opportunity_kit_items', 'product_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_opportunity_kit_items_own_service_id'), 'opportunity_kit_items', ['own_service_id'], unique=False)
    op.create_foreign_key(None, 'opportunity_kit_items', 'own_services', ['own_service_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'opportunity_kit_items', type_='foreignkey')
    op.drop_index(op.f('ix_opportunity_kit_items_own_service_id'), table_name='opportunity_kit_items')
    op.alter_column('opportunity_kit_items', 'product_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('opportunity_kit_items', 'own_service_id')
    op.drop_column('opportunity_kit_items', 'tipo_item')
    # ### end Alembic commands ###
