"""Add catalog models

Revision ID: 15dde4d9aada
Revises: e51788359802
Create Date: 2026-03-04 19:38:37.891708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15dde4d9aada'
down_revision: Union[str, Sequence[str], None] = 'e51788359802'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('states',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('ibge_id', sa.Integer(), nullable=False),
    sa.Column('sigla', sa.String(length=2), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('regiao_nome', sa.String(length=50), nullable=True),
    sa.Column('regiao_sigla', sa.String(length=5), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'ibge_id', name='uq_state_tenant_ibge_id')
    )
    op.create_index(op.f('ix_states_ibge_id'), 'states', ['ibge_id'], unique=False)
    op.create_index(op.f('ix_states_nome'), 'states', ['nome'], unique=False)
    op.create_index(op.f('ix_states_sigla'), 'states', ['sigla'], unique=False)
    op.create_index(op.f('ix_states_tenant_id'), 'states', ['tenant_id'], unique=False)
    op.create_table('cities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('ibge_id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('microregiao', sa.String(length=150), nullable=True),
    sa.Column('mesorregiao', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'ibge_id', name='uq_city_tenant_ibge_id')
    )
    op.create_index(op.f('ix_cities_ibge_id'), 'cities', ['ibge_id'], unique=False)
    op.create_index(op.f('ix_cities_nome'), 'cities', ['nome'], unique=False)
    op.create_index(op.f('ix_cities_state_id'), 'cities', ['state_id'], unique=False)
    op.create_index(op.f('ix_cities_tenant_id'), 'cities', ['tenant_id'], unique=False)
    op.create_table('ibge_sync_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCESS', 'FAILED', name='syncjobstatus'), nullable=False),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('triggered_by_user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ibge_sync_jobs_tenant_id'), 'ibge_sync_jobs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ibge_sync_jobs_tenant_id'), table_name='ibge_sync_jobs')
    op.drop_table('ibge_sync_jobs')
    op.drop_index(op.f('ix_cities_tenant_id'), table_name='cities')
    op.drop_index(op.f('ix_cities_state_id'), table_name='cities')
    op.drop_index(op.f('ix_cities_nome'), table_name='cities')
    op.drop_index(op.f('ix_cities_ibge_id'), table_name='cities')
    op.drop_table('cities')
    op.drop_index(op.f('ix_states_tenant_id'), table_name='states')
    op.drop_index(op.f('ix_states_sigla'), table_name='states')
    op.drop_index(op.f('ix_states_nome'), table_name='states')
    op.drop_index(op.f('ix_states_ibge_id'), table_name='states')
    op.drop_table('states')
    # ### end Alembic commands ###
