"""add_faturamento_servico_separado

Revision ID: 192f5fdfb07f
Revises: 1d438afa0874
Create Date: 2026-04-16 19:01:29.422147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '192f5fdfb07f'
down_revision: Union[str, Sequence[str], None] = '1d438afa0874'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunity_kits', sa.Column('faturamento_servico_separado', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunity_kits', 'faturamento_servico_separado')
    # ### end Alembic commands ###
