"""Add kit_custos_mensais

Revision ID: 1d438afa0874
Revises: a2e163fcc6e4
Create Date: 2026-04-16 18:05:28.365661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d438afa0874'
down_revision: Union[str, Sequence[str], None] = 'a2e163fcc6e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kit_custos_mensais',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kit_id', sa.UUID(), nullable=False),
    sa.Column('servico', sa.String(length=255), nullable=False),
    sa.Column('tipo_custo', sa.String(length=50), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('valor_unitario', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['kit_id'], ['opportunity_kits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kit_custos_mensais_kit_id'), 'kit_custos_mensais', ['kit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kit_custos_mensais_kit_id'), table_name='kit_custos_mensais')
    op.drop_table('kit_custos_mensais')
    # ### end Alembic commands ###
