"""add_dollar_budget_fields

Revision ID: 1ddbe54fdbe6
Revises: 7c169f5b3a11
Create Date: 2026-06-01 18:35:04.694201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ddbe54fdbe6'
down_revision: Union[str, Sequence[str], None] = '7c169f5b3a11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_budget_items', sa.Column('valor_unitario_dolar', sa.Numeric(precision=15, scale=4), nullable=True))
    op.add_column('purchase_budgets', sa.Column('dolar_orcamento', sa.Boolean(), nullable=True))
    op.add_column('purchase_budgets', sa.Column('valor_conversao', sa.Numeric(precision=15, scale=4), nullable=True))
    
    # Populate default value for existing rows
    op.execute("UPDATE purchase_budgets SET dolar_orcamento = FALSE")
    
    # Make the column non-nullable
    op.alter_column('purchase_budgets', 'dolar_orcamento', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_budgets', 'valor_conversao')
    op.drop_column('purchase_budgets', 'dolar_orcamento')
    op.drop_column('purchase_budget_items', 'valor_unitario_dolar')
    # ### end Alembic commands ###
