"""add_missing_budget_columns

Revision ID: 27b9143069e7
Revises: 4051fae153f0
Create Date: 2026-03-10 12:31:08.159387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27b9143069e7'
down_revision: Union[str, Sequence[str], None] = '4051fae153f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunity_budgets', sa.Column('nome_fornecedor_manual', sa.String(length=255), nullable=True))
    op.add_column('opportunity_budgets', sa.Column('cnpj_fornecedor', sa.String(length=20), nullable=True))
    op.add_column('opportunity_budgets', sa.Column('moeda', sa.String(length=10), nullable=True))
    op.add_column('opportunity_budgets', sa.Column('cambio', sa.Numeric(precision=15, scale=6), nullable=True))
    op.add_column('opportunity_budgets', sa.Column('data_cotacao', sa.Date(), nullable=True))
    op.add_column('opportunity_budgets', sa.Column('valor_total_itens', sa.Numeric(precision=18, scale=6), nullable=True))
    op.add_column('opportunity_budgets', sa.Column('valor_total_impostos', sa.Numeric(precision=18, scale=6), nullable=True))
    op.add_column('opportunity_budgets', sa.Column('valor_total_orcamento', sa.Numeric(precision=18, scale=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunity_budgets', 'valor_total_orcamento')
    op.drop_column('opportunity_budgets', 'valor_total_impostos')
    op.drop_column('opportunity_budgets', 'valor_total_itens')
    op.drop_column('opportunity_budgets', 'data_cotacao')
    op.drop_column('opportunity_budgets', 'cambio')
    op.drop_column('opportunity_budgets', 'moeda')
    op.drop_column('opportunity_budgets', 'cnpj_fornecedor')
    op.drop_column('opportunity_budgets', 'nome_fornecedor_manual')
    # ### end Alembic commands ###
