"""add perc_comissao_diretoria

Revision ID: 2ae462a01a6f
Revises: 4e512281a972
Create Date: 2026-03-22 21:21:40.766161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ae462a01a6f'
down_revision: Union[str, Sequence[str], None] = '4e512281a972'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_budgets', sa.Column('perc_comissao_diretoria', sa.Numeric(precision=6, scale=4), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_budgets', 'perc_comissao_diretoria')
    # ### end Alembic commands ###
