"""Add commercial policies models

Revision ID: 2bfbfec6daf7
Revises: f8be831f6665
Create Date: 2026-04-22 16:31:40.198847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bfbfec6daf7'
down_revision: Union[str, Sequence[str], None] = 'f8be831f6665'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_commercial_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('nome_politica', sa.String(length=25), nullable=False),
    sa.Column('fator_limite', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('manutencao_ano_percentual', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('comissao_percentual', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_commercial_policy_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['company_commercial_policies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_commercial_policy_roles')
    op.drop_table('company_commercial_policies')
    # ### end Alembic commands ###
