"""Add Product reference price columns

Revision ID: 33edfc400bac
Revises: fe80a46b6099
Create Date: 2026-03-16 10:47:22.106906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33edfc400bac'
down_revision: Union[str, Sequence[str], None] = 'fe80a46b6099'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('vlr_referencia_revenda', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('products', sa.Column('vlr_referencia_uso_consumo', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('products', sa.Column('orcamento_referencia_revenda_id', sa.UUID(), nullable=True))
    op.add_column('products', sa.Column('orcamento_referencia_uso_consumo_id', sa.UUID(), nullable=True))
    op.add_column('products', sa.Column('data_atualizacao_revenda', sa.DateTime(timezone=True), nullable=True))
    op.add_column('products', sa.Column('data_atualizacao_uso_consumo', sa.DateTime(timezone=True), nullable=True))
    op.add_column('products', sa.Column('origem_valor_uso_consumo', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'products', 'purchase_budgets', ['orcamento_referencia_uso_consumo_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'products', 'purchase_budgets', ['orcamento_referencia_revenda_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'origem_valor_uso_consumo')
    op.drop_column('products', 'data_atualizacao_uso_consumo')
    op.drop_column('products', 'data_atualizacao_revenda')
    op.drop_column('products', 'orcamento_referencia_uso_consumo_id')
    op.drop_column('products', 'orcamento_referencia_revenda_id')
    op.drop_column('products', 'vlr_referencia_uso_consumo')
    op.drop_column('products', 'vlr_referencia_revenda')
    # ### end Alembic commands ###
