"""Add aliq_icms to opportunity_kits

Revision ID: 3c1be10427dc
Revises: 676911d16b82
Create Date: 2026-03-24 13:36:39.847682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c1be10427dc'
down_revision: Union[str, Sequence[str], None] = '676911d16b82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunity_kits', sa.Column('aliq_icms', sa.Numeric(precision=6, scale=4), nullable=False, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunity_kits', 'aliq_icms')
    # ### end Alembic commands ###
