"""add_licitacao_team_and_history

Revision ID: 401accd6f92a
Revises: 7a8e831f7777
Create Date: 2026-06-16 19:37:00.284163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '401accd6f92a'
down_revision: Union[str, Sequence[str], None] = '7a8e831f7777'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('licitacao_analistas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('licitacao_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.String(), nullable=False),
    sa.Column('data_zero', sa.DateTime(timezone=True), nullable=False),
    sa.Column('prazo_dias_uteis', sa.Integer(), nullable=False),
    sa.Column('data_limite', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['licitacao_id'], ['licitacoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licitacao_analistas_licitacao_id'), 'licitacao_analistas', ['licitacao_id'], unique=False)
    op.create_index(op.f('ix_licitacao_analistas_usuario_id'), 'licitacao_analistas', ['usuario_id'], unique=False)
    op.create_table('licitacao_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('licitacao_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.String(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('data_movimentacao', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['licitacao_id'], ['licitacoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licitacao_history_licitacao_id'), 'licitacao_history', ['licitacao_id'], unique=False)
    op.add_column('licitacoes', sa.Column('po_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'licitacoes', 'users', ['po_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'licitacoes', type_='foreignkey')
    op.drop_column('licitacoes', 'po_id')
    op.drop_index(op.f('ix_licitacao_history_licitacao_id'), table_name='licitacao_history')
    op.drop_table('licitacao_history')
    op.drop_index(op.f('ix_licitacao_analistas_usuario_id'), table_name='licitacao_analistas')
    op.drop_index(op.f('ix_licitacao_analistas_licitacao_id'), table_name='licitacao_analistas')
    op.drop_table('licitacao_analistas')
    # ### end Alembic commands ###
