"""add part_number to products

Revision ID: 4051fae153f0
Revises: e9845fcc62d9
Create Date: 2026-03-10 10:42:09.342539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4051fae153f0'
down_revision: Union[str, Sequence[str], None] = 'e9845fcc62d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('part_number', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'part_number')
    # ### end Alembic commands ###
