"""add_company_fiscal_params_opportunities

Revision ID: 405ead5d4919
Revises: fa78168e8d63
Create Date: 2026-03-24 10:58:14.902063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '405ead5d4919'
down_revision: Union[str, Sequence[str], None] = 'fa78168e8d63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('nomenclatura_orcamento', sa.String(length=20), nullable=True))
    op.add_column('companies', sa.Column('numero_proposta', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'numero_proposta')
    op.drop_column('companies', 'nomenclatura_orcamento')
    # ### end Alembic commands ###
