"""add_numero_orcamento_to_purchase_budgets

Revision ID: 4d78633a646e
Revises: 10a1c52fa98e
Create Date: 2026-03-14 09:00:13.444585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d78633a646e'
down_revision: Union[str, Sequence[str], None] = '10a1c52fa98e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_budgets', sa.Column('numero_orcamento', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_budgets', 'numero_orcamento')
    # ### end Alembic commands ###
