"""fator_manutencao_padrao

Revision ID: 4e512281a972
Revises: 94ead9aa0913
Create Date: 2026-03-20 15:53:13.792764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e512281a972'
down_revision: Union[str, Sequence[str], None] = '94ead9aa0913'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_budgets', sa.Column('fator_manutencao_padrao', sa.Numeric(precision=6, scale=4), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_budgets', 'fator_manutencao_padrao')
    # ### end Alembic commands ###
