"""Add opportunity_kit_id to sales items

Revision ID: 598ae93a26f6
Revises: a2ccae627d89
Create Date: 2026-03-24 20:40:05.907703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '598ae93a26f6'
down_revision: Union[str, Sequence[str], None] = 'a2ccae627d89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_budget_items', sa.Column('opportunity_kit_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_sales_budget_items_opportunity_kit_id'), 'sales_budget_items', ['opportunity_kit_id'], unique=False)
    op.create_foreign_key(None, 'sales_budget_items', 'opportunity_kits', ['opportunity_kit_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales_budget_items', type_='foreignkey')
    op.drop_index(op.f('ix_sales_budget_items_opportunity_kit_id'), table_name='sales_budget_items')
    op.drop_column('sales_budget_items', 'opportunity_kit_id')
    # ### end Alembic commands ###
