"""add kit fields

Revision ID: 5d1f92d61122
Revises: 6dcec629161f
Create Date: 2026-03-18 20:23:10.359195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d1f92d61122'
down_revision: Union[str, Sequence[str], None] = '6dcec629161f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental_budget_items', sa.Column('tipo_contrato_kit', sa.String(length=50), nullable=True))
    op.add_column('rental_budget_items', sa.Column('kit_taxa_juros_mensal', sa.Numeric(precision=15, scale=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rental_budget_items', 'kit_taxa_juros_mensal')
    op.drop_column('rental_budget_items', 'tipo_contrato_kit')
    # ### end Alembic commands ###
