"""Add CNPJ integration fields

Revision ID: 6055cddcb0a6
Revises: 3d7c3b9e4a12
Create Date: 2026-03-06 17:06:15.825034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6055cddcb0a6'
down_revision: Union[str, Sequence[str], None] = '3d7c3b9e4a12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cnpj_query_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('response_body_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mapped_body_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hash_resposta', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cnpj_query_cache_cnpj'), 'cnpj_query_cache', ['cnpj'], unique=False)
    op.create_table('company_cnpj_query_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('cnpj_consultado', sa.String(length=14), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('provider_status', sa.String(length=50), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('from_cache', sa.Boolean(), nullable=True),
    sa.Column('response_body_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mapped_body_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('consulted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consulted_by_user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_qsa',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('qualificacao', sa.String(length=255), nullable=True),
    sa.Column('pais_origem', sa.String(length=255), nullable=True),
    sa.Column('nome_rep_legal', sa.String(length=255), nullable=True),
    sa.Column('qualificacao_rep_legal', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('cnae_catalog', 'descricao',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.add_column('companies', sa.Column('cnpj_consultado_em', sa.DateTime(timezone=True), nullable=True))
    op.add_column('companies', sa.Column('cnpj_consulta_origem', sa.String(length=50), nullable=True))
    op.add_column('companies', sa.Column('cnpj_json_ultimo_retorno', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('companies', sa.Column('cnpj_status_ultima_consulta', sa.String(length=50), nullable=True))
    op.add_column('companies', sa.Column('cnpj_mensagem_ultima_consulta', sa.String(length=255), nullable=True))
    op.drop_index(op.f('idx_companies_tenant_cnpj'), table_name='companies')
    op.alter_column('company_benefits', 'observacao',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_company_cnaes_primary'), table_name='company_cnaes', postgresql_where="((tipo)::text = 'PRIMARIO'::text)")
    op.drop_index(op.f('idx_company_cnaes_unique'), table_name='company_cnaes')
    op.alter_column('company_tax_profiles', 'observacoes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_tax_profiles_active'), table_name='company_tax_profiles', postgresql_where='(vigencia_fim IS NULL)')
    op.alter_column('tax_benefits', 'descricao',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tax_benefits', 'descricao',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index(op.f('idx_tax_profiles_active'), 'company_tax_profiles', ['company_id'], unique=True, postgresql_where='(vigencia_fim IS NULL)')
    op.alter_column('company_tax_profiles', 'observacoes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index(op.f('idx_company_cnaes_unique'), 'company_cnaes', ['company_id', 'cnae_codigo'], unique=True)
    op.create_index(op.f('idx_company_cnaes_primary'), 'company_cnaes', ['company_id'], unique=True, postgresql_where="((tipo)::text = 'PRIMARIO'::text)")
    op.alter_column('company_benefits', 'observacao',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index(op.f('idx_companies_tenant_cnpj'), 'companies', ['tenant_id', 'cnpj'], unique=True)
    op.drop_column('companies', 'cnpj_mensagem_ultima_consulta')
    op.drop_column('companies', 'cnpj_status_ultima_consulta')
    op.drop_column('companies', 'cnpj_json_ultimo_retorno')
    op.drop_column('companies', 'cnpj_consulta_origem')
    op.drop_column('companies', 'cnpj_consultado_em')
    op.alter_column('cnae_catalog', 'descricao',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_table('company_qsa')
    op.drop_table('company_cnpj_query_logs')
    op.drop_index(op.f('ix_cnpj_query_cache_cnpj'), table_name='cnpj_query_cache')
    op.drop_table('cnpj_query_cache')
    # ### end Alembic commands ###
