"""add_solution_analysis

Revision ID: 628ea409ff67
Revises: 4d7e1d185dec
Create Date: 2026-03-27 19:23:00.258570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '628ea409ff67'
down_revision: Union[str, Sequence[str], None] = '4d7e1d185dec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solution_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('tipo_analise', sa.String(length=20), nullable=False),
    sa.Column('nome_solucao_a', sa.String(length=100), nullable=True),
    sa.Column('nome_solucao_b', sa.String(length=100), nullable=True),
    sa.Column('nome_solucao_c', sa.String(length=100), nullable=True),
    sa.Column('usuario_id', sa.String(), nullable=True),
    sa.Column('criado_por_nome', sa.String(length=255), nullable=True),
    sa.Column('ultima_alteracao_por_id', sa.String(), nullable=True),
    sa.Column('ultima_alteracao_por_nome', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ultima_alteracao_por_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solution_analyses_company_id'), 'solution_analyses', ['company_id'], unique=False)
    op.create_index(op.f('ix_solution_analyses_tenant_id'), 'solution_analyses', ['tenant_id'], unique=False)
    op.create_table('solution_analysis_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analise_id', sa.UUID(), nullable=False),
    sa.Column('sequencia', sa.Integer(), nullable=False),
    sa.Column('item_a_id', sa.UUID(), nullable=True),
    sa.Column('item_a_nome', sa.String(length=255), nullable=True),
    sa.Column('qtd_a', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('vlr_unit_a', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('vlr_total_a', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('item_b_id', sa.UUID(), nullable=True),
    sa.Column('item_b_nome', sa.String(length=255), nullable=True),
    sa.Column('qtd_b', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('vlr_unit_b', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('vlr_total_b', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('item_c_id', sa.UUID(), nullable=True),
    sa.Column('item_c_nome', sa.String(length=255), nullable=True),
    sa.Column('qtd_c', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('vlr_unit_c', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('vlr_total_c', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('melhor_solucao', sa.String(length=10), nullable=True),
    sa.Column('diferenca_valor', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('diferenca_percentual', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analise_id'], ['solution_analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_a_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_b_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_c_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solution_analysis_items_analise_id'), 'solution_analysis_items', ['analise_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solution_analysis_items_analise_id'), table_name='solution_analysis_items')
    op.drop_table('solution_analysis_items')
    op.drop_index(op.f('ix_solution_analyses_tenant_id'), table_name='solution_analyses')
    op.drop_index(op.f('ix_solution_analyses_company_id'), table_name='solution_analyses')
    op.drop_table('solution_analyses')
    # ### end Alembic commands ###
