"""add_ncm_tables

Revision ID: 62e2752266b9
Revises: 04a8f746b8f2
Create Date: 2026-03-07 20:42:03.042490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62e2752266b9'
down_revision: Union[str, Sequence[str], None] = '04a8f746b8f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ncm_importacao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('data_ultima_atualizacao_ncm', sa.String(length=50), nullable=True),
    sa.Column('ato', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ncm',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('importacao_id', sa.UUID(), nullable=True),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('tipo_ato_ini', sa.String(length=100), nullable=True),
    sa.Column('numero_ato_ini', sa.String(length=20), nullable=True),
    sa.Column('ano_ato_ini', sa.String(length=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['importacao_id'], ['ncm_importacao.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo', 'data_inicio', 'data_fim', name='uq_ncm_codigo_vigencia')
    )
    op.create_index(op.f('ix_ncm_codigo'), 'ncm', ['codigo'], unique=False)
    op.create_index('ix_ncm_codigo_vigencia', 'ncm', ['codigo', 'data_inicio', 'data_fim'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ncm_codigo_vigencia', table_name='ncm')
    op.drop_index(op.f('ix_ncm_codigo'), table_name='ncm')
    op.drop_table('ncm')
    op.drop_table('ncm_importacao')
    # ### end Alembic commands ###
