"""Add Venda de Equipamentos params to Opportunity Kits

Revision ID: 676911d16b82
Revises: 07761b74db46
Create Date: 2026-03-24 12:57:27.494181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '676911d16b82'
down_revision: Union[str, Sequence[str], None] = '07761b74db46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunity_kits', sa.Column('fator_margem_instalacao', sa.Numeric(precision=10, scale=4), nullable=False, server_default=sa.text('1.0')))
    op.add_column('opportunity_kits', sa.Column('fator_margem_manutencao', sa.Numeric(precision=10, scale=4), nullable=False, server_default=sa.text('1.0')))
    op.add_column('opportunity_kits', sa.Column('havera_manutencao', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('opportunity_kits', sa.Column('qtd_meses_manutencao', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunity_kits', 'qtd_meses_manutencao')
    op.drop_column('opportunity_kits', 'havera_manutencao')
    op.drop_column('opportunity_kits', 'fator_margem_manutencao')
    op.drop_column('opportunity_kits', 'fator_margem_instalacao')
    # ### end Alembic commands ###
