"""Add instalacao and manutencao flags to kits

Revision ID: 6b38c93e641c
Revises: 6c84f66bb348
Create Date: 2026-03-19 19:46:37.116514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b38c93e641c'
down_revision: Union[str, Sequence[str], None] = '6c84f66bb348'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunity_kits', sa.Column('instalacao_inclusa', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('opportunity_kits', sa.Column('percentual_instalacao', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('opportunity_kits', sa.Column('manutencao_inclusa', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('opportunity_kits', sa.Column('fator_manutencao', sa.Numeric(precision=10, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunity_kits', 'fator_manutencao')
    op.drop_column('opportunity_kits', 'manutencao_inclusa')
    op.drop_column('opportunity_kits', 'percentual_instalacao')
    op.drop_column('opportunity_kits', 'instalacao_inclusa')
    # ### end Alembic commands ###
