"""Add OpportunityKitCost table

Revision ID: 6c84f66bb348
Revises: 5d1f92d61122
Create Date: 2026-03-19 11:46:48.674481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c84f66bb348'
down_revision: Union[str, Sequence[str], None] = '5d1f92d61122'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunity_kit_costs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kit_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('tipo_custo', sa.String(length=50), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('valor_unitario', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['kit_id'], ['opportunity_kits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunity_kit_costs_kit_id'), 'opportunity_kit_costs', ['kit_id'], unique=False)
    op.create_index(op.f('ix_opportunity_kit_costs_product_id'), 'opportunity_kit_costs', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunity_kit_costs_product_id'), table_name='opportunity_kit_costs')
    op.drop_index(op.f('ix_opportunity_kit_costs_kit_id'), table_name='opportunity_kit_costs')
    op.drop_table('opportunity_kit_costs')
    # ### end Alembic commands ###
