"""Add detailed kit fields to RentalBudgetItem

Revision ID: 6dcec629161f
Revises: 9cd1ac71d32d
Create Date: 2026-03-18 18:32:27.637012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dcec629161f'
down_revision: Union[str, Sequence[str], None] = '9cd1ac71d32d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental_budget_items', sa.Column('is_kit_instalacao', sa.Boolean(), nullable=False))
    op.add_column('rental_budget_items', sa.Column('kit_custo_produtos', sa.Numeric(precision=15, scale=4), nullable=True))
    op.add_column('rental_budget_items', sa.Column('kit_custo_servicos', sa.Numeric(precision=15, scale=4), nullable=True))
    op.add_column('rental_budget_items', sa.Column('kit_pis', sa.Numeric(precision=6, scale=4), nullable=True))
    op.add_column('rental_budget_items', sa.Column('kit_cofins', sa.Numeric(precision=6, scale=4), nullable=True))
    op.add_column('rental_budget_items', sa.Column('kit_csll', sa.Numeric(precision=6, scale=4), nullable=True))
    op.add_column('rental_budget_items', sa.Column('kit_irpj', sa.Numeric(precision=6, scale=4), nullable=True))
    op.add_column('rental_budget_items', sa.Column('kit_iss', sa.Numeric(precision=6, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rental_budget_items', 'kit_iss')
    op.drop_column('rental_budget_items', 'kit_irpj')
    op.drop_column('rental_budget_items', 'kit_csll')
    op.drop_column('rental_budget_items', 'kit_cofins')
    op.drop_column('rental_budget_items', 'kit_pis')
    op.drop_column('rental_budget_items', 'kit_custo_servicos')
    op.drop_column('rental_budget_items', 'kit_custo_produtos')
    op.drop_column('rental_budget_items', 'is_kit_instalacao')
    # ### end Alembic commands ###
