"""add data_limite_questionamento

Revision ID: 7a8e831f7777
Revises: 91e4386c2251
Create Date: 2026-06-16 14:40:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a8e831f7777'
down_revision: Union[str, Sequence[str], None] = '91e4386c2251'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('licitacoes', sa.Column('data_limite_questionamento', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('licitacoes', 'data_limite_questionamento')
    # ### end Alembic commands ###
