"""Add sales_budget_id to PurchaseBudget

Revision ID: 8bb09b607a5b
Revises: 2ae462a01a6f
Create Date: 2026-03-23 15:59:10.165124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bb09b607a5b'
down_revision: Union[str, Sequence[str], None] = '2ae462a01a6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_budgets', sa.Column('sales_budget_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_purchase_budgets_sales_budget_id'), 'purchase_budgets', ['sales_budget_id'], unique=False)
    op.create_foreign_key(None, 'purchase_budgets', 'sales_budgets', ['sales_budget_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase_budgets', type_='foreignkey')
    op.drop_index(op.f('ix_purchase_budgets_sales_budget_id'), table_name='purchase_budgets')
    op.drop_column('purchase_budgets', 'sales_budget_id')
    # ### end Alembic commands ###
