"""Add CompanySalesParameter

Revision ID: 8d8bf5324cdb
Revises: cca21a85e82d
Create Date: 2026-03-09 18:16:11.702122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d8bf5324cdb'
down_revision: Union[str, Sequence[str], None] = 'cca21a85e82d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_sales_parameters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('mkp_padrao', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('despesa_administrativa', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('comissionamento', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pis', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cofins', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('csll', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('irpj', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('iss', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('icms_interno', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('icms_externo', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_sales_parameters')
    # ### end Alembic commands ###
