"""add_licitacoes_module

Revision ID: 91e4386c2251
Revises: 1ddbe54fdbe6
Create Date: 2026-06-16 15:23:46.602143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91e4386c2251'
down_revision: Union[str, Sequence[str], None] = '1ddbe54fdbe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('licitacoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('numero_edital', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_publicacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_licitacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('modalidade', sa.String(length=50), nullable=False),
    sa.Column('tipo_licitacao', sa.String(length=50), nullable=False),
    sa.Column('valor_total_estimado', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('valor_total_venda', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('margem_ponderada_global', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('precisa_aprovacao_diretoria', sa.Boolean(), nullable=False),
    sa.Column('aprovado_diretoria', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licitacoes_company_id'), 'licitacoes', ['company_id'], unique=False)
    op.create_index(op.f('ix_licitacoes_customer_id'), 'licitacoes', ['customer_id'], unique=False)
    op.create_index(op.f('ix_licitacoes_tenant_id'), 'licitacoes', ['tenant_id'], unique=False)
    op.create_table('licitacao_lotes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('licitacao_id', sa.UUID(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['licitacao_id'], ['licitacoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licitacao_lotes_licitacao_id'), 'licitacao_lotes', ['licitacao_id'], unique=False)
    op.create_table('licitacao_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lote_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('quantidade', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lote_id'], ['licitacao_lotes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licitacao_items_lote_id'), 'licitacao_items', ['lote_id'], unique=False)
    op.add_column('opportunity_kits', sa.Column('licitacao_id', sa.UUID(), nullable=True))
    op.add_column('opportunity_kits', sa.Column('licitacao_item_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_opportunity_kits_licitacao_id'), 'opportunity_kits', ['licitacao_id'], unique=False)
    op.create_index(op.f('ix_opportunity_kits_licitacao_item_id'), 'opportunity_kits', ['licitacao_item_id'], unique=False)
    op.create_foreign_key(None, 'opportunity_kits', 'licitacoes', ['licitacao_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'opportunity_kits', 'licitacao_items', ['licitacao_item_id'], ['id'], ondelete='CASCADE')
    op.alter_column('products', 'nome',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=300),
               existing_nullable=False)
    op.add_column('purchase_budgets', sa.Column('licitacao_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_purchase_budgets_licitacao_id'), 'purchase_budgets', ['licitacao_id'], unique=False)
    op.create_foreign_key(None, 'purchase_budgets', 'licitacoes', ['licitacao_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase_budgets', type_='foreignkey')
    op.drop_index(op.f('ix_purchase_budgets_licitacao_id'), table_name='purchase_budgets')
    op.drop_column('purchase_budgets', 'licitacao_id')
    op.alter_column('products', 'nome',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_constraint(None, 'opportunity_kits', type_='foreignkey')
    op.drop_constraint(None, 'opportunity_kits', type_='foreignkey')
    op.drop_index(op.f('ix_opportunity_kits_licitacao_item_id'), table_name='opportunity_kits')
    op.drop_index(op.f('ix_opportunity_kits_licitacao_id'), table_name='opportunity_kits')
    op.drop_column('opportunity_kits', 'licitacao_item_id')
    op.drop_column('opportunity_kits', 'licitacao_id')
    op.drop_index(op.f('ix_licitacao_items_lote_id'), table_name='licitacao_items')
    op.drop_table('licitacao_items')
    op.drop_index(op.f('ix_licitacao_lotes_licitacao_id'), table_name='licitacao_lotes')
    op.drop_table('licitacao_lotes')
    op.drop_index(op.f('ix_licitacoes_tenant_id'), table_name='licitacoes')
    op.drop_index(op.f('ix_licitacoes_customer_id'), table_name='licitacoes')
    op.drop_index(op.f('ix_licitacoes_company_id'), table_name='licitacoes')
    op.drop_table('licitacoes')
    # ### end Alembic commands ###
