"""Add sales budget id

Revision ID: 94ead9aa0913
Revises: 6b38c93e641c
Create Date: 2026-03-20 12:20:01.829174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94ead9aa0913'
down_revision: Union[str, Sequence[str], None] = '6b38c93e641c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunity_kits', sa.Column('sales_budget_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_opportunity_kits_sales_budget_id'), 'opportunity_kits', ['sales_budget_id'], unique=False)
    op.create_foreign_key(None, 'opportunity_kits', 'sales_budgets', ['sales_budget_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'opportunity_kits', type_='foreignkey')
    op.drop_index(op.f('ix_opportunity_kits_sales_budget_id'), table_name='opportunity_kits')
    op.drop_column('opportunity_kits', 'sales_budget_id')
    # ### end Alembic commands ###
