"""Add UserCompany association

Revision ID: 991fd04fa7f9
Revises: 27b9143069e7
Create Date: 2026-03-12 03:20:50.928664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '991fd04fa7f9'
down_revision: Union[str, Sequence[str], None] = '27b9143069e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_companies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('opportunity_budget_items', sa.Column('uf_origem', sa.String(length=2), nullable=True))
    op.add_column('opportunity_budget_items', sa.Column('uf_destino', sa.String(length=2), nullable=True))
    op.add_column('opportunity_budget_items', sa.Column('operacao_interestadual', sa.Boolean(), nullable=True))
    op.add_column('opportunity_budget_items', sa.Column('aliquota_orcamento_aplicada', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('opportunity_budget_items', sa.Column('aliquota_interna_destino', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('opportunity_budget_items', sa.Column('valor_icms_origem', sa.Numeric(precision=15, scale=6), nullable=True))
    op.add_column('opportunity_budget_items', sa.Column('valor_difal_base', sa.Numeric(precision=15, scale=6), nullable=True))
    op.add_column('opportunity_budget_items', sa.Column('valor_icms_st', sa.Numeric(precision=15, scale=6), nullable=True))
    op.add_column('opportunity_budget_items', sa.Column('diferenca_difal_st', sa.Numeric(precision=15, scale=6), nullable=True))
    op.add_column('opportunity_budget_items', sa.Column('valor_difal_aplicado', sa.Numeric(precision=15, scale=6), nullable=True))
    op.add_column('opportunity_budget_items', sa.Column('custo_com_difal', sa.Numeric(precision=15, scale=6), nullable=True))
    op.add_column('opportunity_budget_items', sa.Column('criar_cenario_difal_aplicado', sa.Boolean(), nullable=True))
    op.add_column('opportunity_budgets', sa.Column('aliquota_orcamento', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('opportunity_budgets', sa.Column('criar_cenario_difal', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunity_budgets', 'criar_cenario_difal')
    op.drop_column('opportunity_budgets', 'aliquota_orcamento')
    op.drop_column('opportunity_budget_items', 'criar_cenario_difal_aplicado')
    op.drop_column('opportunity_budget_items', 'custo_com_difal')
    op.drop_column('opportunity_budget_items', 'valor_difal_aplicado')
    op.drop_column('opportunity_budget_items', 'diferenca_difal_st')
    op.drop_column('opportunity_budget_items', 'valor_icms_st')
    op.drop_column('opportunity_budget_items', 'valor_difal_base')
    op.drop_column('opportunity_budget_items', 'valor_icms_origem')
    op.drop_column('opportunity_budget_items', 'aliquota_interna_destino')
    op.drop_column('opportunity_budget_items', 'aliquota_orcamento_aplicada')
    op.drop_column('opportunity_budget_items', 'operacao_interestadual')
    op.drop_column('opportunity_budget_items', 'uf_destino')
    op.drop_column('opportunity_budget_items', 'uf_origem')
    op.drop_table('user_companies')
    # ### end Alembic commands ###
