"""Make OpportunityKit global

Revision ID: 99fb3a0d1201
Revises: a943132f0b48
Create Date: 2026-03-18 12:21:42.430895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99fb3a0d1201'
down_revision: Union[str, Sequence[str], None] = 'a943132f0b48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunity_kits', sa.Column('tenant_id', sa.String(), nullable=False))
    op.add_column('opportunity_kits', sa.Column('company_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_opportunity_kits_budget_id'), table_name='opportunity_kits')
    op.create_index(op.f('ix_opportunity_kits_company_id'), 'opportunity_kits', ['company_id'], unique=False)
    op.create_index(op.f('ix_opportunity_kits_tenant_id'), 'opportunity_kits', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('opportunity_kits_budget_id_fkey'), 'opportunity_kits', type_='foreignkey')
    op.create_foreign_key(None, 'opportunity_kits', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'opportunity_kits', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_column('opportunity_kits', 'budget_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunity_kits', sa.Column('budget_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'opportunity_kits', type_='foreignkey')
    op.drop_constraint(None, 'opportunity_kits', type_='foreignkey')
    op.create_foreign_key(op.f('opportunity_kits_budget_id_fkey'), 'opportunity_kits', 'sales_budgets', ['budget_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_opportunity_kits_tenant_id'), table_name='opportunity_kits')
    op.drop_index(op.f('ix_opportunity_kits_company_id'), table_name='opportunity_kits')
    op.create_index(op.f('ix_opportunity_kits_budget_id'), 'opportunity_kits', ['budget_id'], unique=False)
    op.drop_column('opportunity_kits', 'company_id')
    op.drop_column('opportunity_kits', 'tenant_id')
    # ### end Alembic commands ###
