"""add_kit_despesas_adm_to_rental_items

Revision ID: 9b47f7a58a9c
Revises: 7c31db4f2893
Create Date: 2026-07-04 11:08:22.629127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b47f7a58a9c'
down_revision: Union[str, Sequence[str], None] = '7c31db4f2893'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_companies_tenant_cnpj'), table_name='companies')
    op.drop_index(op.f('idx_company_cnaes_primary'), table_name='company_cnaes', postgresql_where="((tipo)::text = 'PRIMARIO'::text)")
    op.drop_index(op.f('idx_company_cnaes_unique'), table_name='company_cnaes')
    op.drop_index(op.f('idx_tax_profiles_active'), table_name='company_tax_profiles', postgresql_where='(vigencia_fim IS NULL)')
    op.add_column('rental_budget_items', sa.Column('kit_despesas_adm', sa.Numeric(precision=15, scale=4), nullable=True))
    op.add_column('rental_budget_items', sa.Column('kit_perc_despesas_adm', sa.Numeric(precision=6, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rental_budget_items', 'kit_perc_despesas_adm')
    op.drop_column('rental_budget_items', 'kit_despesas_adm')
    op.create_index(op.f('idx_tax_profiles_active'), 'company_tax_profiles', ['company_id'], unique=True, postgresql_where='(vigencia_fim IS NULL)')
    op.create_index(op.f('idx_company_cnaes_unique'), 'company_cnaes', ['company_id', 'cnae_codigo'], unique=True)
    op.create_index(op.f('idx_company_cnaes_primary'), 'company_cnaes', ['company_id'], unique=True, postgresql_where="((tipo)::text = 'PRIMARIO'::text)")
    op.create_index(op.f('idx_companies_tenant_cnpj'), 'companies', ['tenant_id', 'cnpj'], unique=True)
    # ### end Alembic commands ###
