"""Add custo_op_mensal_kit to RentalBudgetItem

Revision ID: 9cd1ac71d32d
Revises: bc5f48d08153
Create Date: 2026-03-18 17:57:01.372025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cd1ac71d32d'
down_revision: Union[str, Sequence[str], None] = 'bc5f48d08153'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental_budget_items', sa.Column('custo_op_mensal_kit', sa.Numeric(precision=15, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rental_budget_items', 'custo_op_mensal_kit')
    # ### end Alembic commands ###
