"""increase_taxa_manutencao_anual_precision

Revision ID: a2e163fcc6e4
Revises: dca8db58ff4e
Create Date: 2026-04-09 13:28:42.267634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2e163fcc6e4'
down_revision: Union[str, Sequence[str], None] = 'dca8db58ff4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('opportunity_kits', 'taxa_manutencao_anual',
               existing_type=sa.NUMERIC(precision=6, scale=4),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('opportunity_kits', 'taxa_manutencao_anual',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.NUMERIC(precision=6, scale=4),
               existing_nullable=False)
    # ### end Alembic commands ###
