"""opportunity_kits

Revision ID: a943132f0b48
Revises: 0ccb8ee54fa0
Create Date: 2026-03-17 19:25:14.653862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a943132f0b48'
down_revision: Union[str, Sequence[str], None] = '0ccb8ee54fa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rental_budget_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('budget_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('quantidade', sa.Numeric(precision=15, scale=4), server_default='1', nullable=False),
    sa.Column('custo_aquisicao_unit', sa.Numeric(precision=15, scale=4), server_default='0', nullable=False),
    sa.Column('ipi_unit', sa.Numeric(precision=15, scale=4), server_default='0', nullable=False),
    sa.Column('frete_unit', sa.Numeric(precision=15, scale=4), server_default='0', nullable=False),
    sa.Column('icms_st_unit', sa.Numeric(precision=15, scale=4), server_default='0', nullable=False),
    sa.Column('difal_unit', sa.Numeric(precision=15, scale=4), server_default='0', nullable=False),
    sa.Column('custo_total_aquisicao', sa.Numeric(precision=15, scale=4), server_default='0', nullable=False),
    sa.Column('prazo_contrato', sa.Integer(), server_default='36', nullable=False),
    sa.Column('usa_taxa_manut_padrao', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('taxa_manutencao_anual_item', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('perc_instalacao_item', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('valor_instalacao_item', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('custo_manut_mensal', sa.Numeric(precision=15, scale=4), server_default='0', nullable=False),
    sa.Column('custo_total_mensal', sa.Numeric(precision=15, scale=4), server_default='0', nullable=False),
    sa.Column('fator_margem', sa.Numeric(precision=10, scale=4), server_default='1', nullable=False),
    sa.Column('valor_venda_equipamento', sa.Numeric(precision=15, scale=4), server_default='0', nullable=False),
    sa.Column('parcela_locacao', sa.Numeric(precision=15, scale=4), server_default='0', nullable=False),
    sa.Column('manutencao_locacao', sa.Numeric(precision=15, scale=4), server_default='0', nullable=False),
    sa.Column('valor_mensal', sa.Numeric(precision=15, scale=4), server_default='0', nullable=False),
    sa.Column('perc_impostos_total', sa.Numeric(precision=6, scale=4), server_default='0', nullable=False),
    sa.Column('impostos_mensal', sa.Numeric(precision=15, scale=4), server_default='0', nullable=False),
    sa.Column('receita_liquida_mensal', sa.Numeric(precision=15, scale=4), server_default='0', nullable=False),
    sa.Column('perc_comissao', sa.Numeric(precision=6, scale=4), server_default='0', nullable=False),
    sa.Column('comissao_mensal', sa.Numeric(precision=15, scale=4), server_default='0', nullable=False),
    sa.Column('lucro_mensal', sa.Numeric(precision=15, scale=4), server_default='0', nullable=False),
    sa.Column('margem', sa.Numeric(precision=10, scale=4), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['sales_budgets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunity_kits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('budget_id', sa.UUID(), nullable=False),
    sa.Column('nome_kit', sa.String(length=255), nullable=False),
    sa.Column('descricao_kit', sa.Text(), nullable=True),
    sa.Column('quantidade_kits', sa.Integer(), nullable=False),
    sa.Column('tipo_contrato', sa.String(length=50), nullable=False),
    sa.Column('considerar_st_ou_difal', sa.String(length=50), nullable=False, server_default='DIFAL'),
    sa.Column('prazo_contrato_meses', sa.Integer(), nullable=False),
    sa.Column('prazo_instalacao_meses', sa.Integer(), nullable=False),
    sa.Column('fator_margem_locacao', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('taxa_juros_mensal', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('taxa_manutencao_anual', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('aliq_pis', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('aliq_cofins', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('aliq_csll', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('aliq_irpj', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('aliq_iss', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('custo_manut_mensal_kit', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('custo_suporte_mensal_kit', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('custo_seguro_mensal_kit', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('custo_logistica_mensal_kit', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('custo_software_mensal_kit', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('custo_itens_acessorios_mensal_kit', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['sales_budgets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunity_kits_budget_id'), 'opportunity_kits', ['budget_id'], unique=False)
    op.create_table('opportunity_kit_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kit_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('descricao_item', sa.String(length=255), nullable=False),
    sa.Column('quantidade_no_kit', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['kit_id'], ['opportunity_kits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunity_kit_items_kit_id'), 'opportunity_kit_items', ['kit_id'], unique=False)
    op.create_index(op.f('ix_opportunity_kit_items_product_id'), 'opportunity_kit_items', ['product_id'], unique=False)
    op.execute("DROP INDEX IF EXISTS idx_rental_budget_items_budget")
    op.execute("DROP INDEX IF EXISTS idx_rental_budget_items_product")
    op.create_index(op.f('ix_rental_budget_items_budget_id'), 'rental_budget_items', ['budget_id'], unique=False)
    op.create_index(op.f('ix_rental_budget_items_product_id'), 'rental_budget_items', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rental_budget_items_product_id'), table_name='rental_budget_items')
    op.drop_index(op.f('ix_rental_budget_items_budget_id'), table_name='rental_budget_items')
    op.create_index(op.f('idx_rental_budget_items_product'), 'rental_budget_items', ['product_id'], unique=False)
    op.create_index(op.f('idx_rental_budget_items_budget'), 'rental_budget_items', ['budget_id'], unique=False)
    op.drop_index(op.f('ix_opportunity_kit_items_product_id'), table_name='opportunity_kit_items')
    op.drop_index(op.f('ix_opportunity_kit_items_kit_id'), table_name='opportunity_kit_items')
    op.drop_table('opportunity_kit_items')
    op.drop_index(op.f('ix_opportunity_kits_budget_id'), table_name='opportunity_kits')
    op.drop_table('opportunity_kits')
    op.drop_table('rental_budget_items')
    # ### end Alembic commands ###
