"""add_company_id_to_professionals

Revision ID: abc123def456
Revises: 192f5fdfb07f
Create Date: 2026-04-17 18:12:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'abc123def456'
down_revision: Union[str, Sequence[str], None] = '192f5fdfb07f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professionals', sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(
        'fk_professionals_company_id', 
        'professionals', 
        'companies', 
        ['company_id'], 
        ['id'], 
        ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_professionals_company_id', 'professionals', type_='foreignkey')
    op.drop_column('professionals', 'company_id')
    # ### end Alembic commands ###
