"""drop opportunities tables

Revision ID: ac7a3f695c3d
Revises: 991fd04fa7f9
Create Date: 2026-03-14 06:44:41.539642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac7a3f695c3d'
down_revision: Union[str, Sequence[str], None] = '991fd04fa7f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opportunity_budget_items')
    op.drop_table('opportunity_items_kit')
    op.drop_table('opportunity_installation_items')
    op.drop_table('opportunity_maintenance_items')
    op.drop_table('opportunity_parameters_sales')
    op.drop_table('opportunity_parameters_rent')
    op.drop_table('opportunity_budgets')
    op.drop_table('opportunity_items')
    op.drop_table('opportunities')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunity_items_kit',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('item_pai_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('produto_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('quantidade', sa.NUMERIC(precision=15, scale=4), autoincrement=False, nullable=True),
    sa.Column('observacoes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['item_pai_id'], ['opportunity_items.id'], name=op.f('opportunity_items_kit_item_pai_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_id'], ['products.id'], name=op.f('opportunity_items_kit_produto_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('opportunity_items_kit_pkey'))
    )
    op.create_table('opportunities',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('numero_oportunidade', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('titulo_oportunidade', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('cliente_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tipo_cliente', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('tipo_operacao', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('possui_instalacao', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('possui_manutencao', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('data_abertura', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('responsavel_comercial', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('origem_oportunidade', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('observacoes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('empresa_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('perfil_tributario_origem_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('valor_total_calculado', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('margem_estimada', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['customers.id'], name=op.f('opportunities_cliente_id_fkey')),
    sa.ForeignKeyConstraint(['empresa_id'], ['companies.id'], name=op.f('opportunities_empresa_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['perfil_tributario_origem_id'], ['company_tax_profiles.id'], name=op.f('opportunities_perfil_tributario_origem_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('opportunities_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('opportunities_pkey')),
    sa.UniqueConstraint('numero_oportunidade', name=op.f('opportunities_numero_oportunidade_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('opportunity_budget_items',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('orcamento_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('codigo_fornecedor', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('descricao', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('quantidade', sa.NUMERIC(precision=15, scale=4), autoincrement=False, nullable=True),
    sa.Column('unidade', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('ncm', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('ipi_percentual', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('icms_percentual', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('valor_unitario', sa.NUMERIC(precision=15, scale=6), autoincrement=False, nullable=True),
    sa.Column('produto_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('oportunidade_item_id_vinculado', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('uf_origem', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('uf_destino', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('operacao_interestadual', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('aliquota_orcamento_aplicada', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('aliquota_interna_destino', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('valor_icms_origem', sa.NUMERIC(precision=15, scale=6), autoincrement=False, nullable=True),
    sa.Column('valor_difal_base', sa.NUMERIC(precision=15, scale=6), autoincrement=False, nullable=True),
    sa.Column('valor_icms_st', sa.NUMERIC(precision=15, scale=6), autoincrement=False, nullable=True),
    sa.Column('diferenca_difal_st', sa.NUMERIC(precision=15, scale=6), autoincrement=False, nullable=True),
    sa.Column('valor_difal_aplicado', sa.NUMERIC(precision=15, scale=6), autoincrement=False, nullable=True),
    sa.Column('custo_com_difal', sa.NUMERIC(precision=15, scale=6), autoincrement=False, nullable=True),
    sa.Column('criar_cenario_difal_aplicado', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['oportunidade_item_id_vinculado'], ['opportunity_items.id'], name=op.f('opportunity_budget_items_oportunidade_item_id_vinculado_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['orcamento_id'], ['opportunity_budgets.id'], name=op.f('opportunity_budget_items_orcamento_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_id'], ['products.id'], name=op.f('opportunity_budget_items_produto_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('opportunity_budget_items_pkey'))
    )
    op.create_table('opportunity_parameters_rent',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('opportunity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('prazo_contrato_meses', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tipo_receita', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('modo_precificacao', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('margem_padrao_percentual', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('comissao_receita_liquida_percentual', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('pis_percentual', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('cofins_percentual', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('irpj_percentual', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('csll_percentual', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('iss_percentual', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('fator_margem_locacao', sa.NUMERIC(precision=14, scale=6), autoincrement=False, nullable=True),
    sa.Column('taxa_juros_mensal_percentual', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('taxa_manutencao_anual_percentual', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('opportunity_parameters_rent_opportunity_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('opportunity_parameters_rent_pkey')),
    sa.UniqueConstraint('opportunity_id', name=op.f('opportunity_parameters_rent_opportunity_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('opportunity_maintenance_items',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('opportunity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('oportunidade_item_id_relacionado', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('produto_servico_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('quantidade', sa.NUMERIC(precision=15, scale=4), autoincrement=False, nullable=True),
    sa.Column('valor_unitario', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('observacoes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['oportunidade_item_id_relacionado'], ['opportunity_items.id'], name=op.f('opportunity_maintenance_items_oportunidade_item_id_relacio_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('opportunity_maintenance_items_opportunity_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_servico_id'], ['products.id'], name=op.f('opportunity_maintenance_items_produto_servico_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('opportunity_maintenance_items_pkey'))
    )
    op.create_table('opportunity_installation_items',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('opportunity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('oportunidade_item_id_relacionado', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('produto_servico_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('quantidade', sa.NUMERIC(precision=15, scale=4), autoincrement=False, nullable=True),
    sa.Column('valor_unitario', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('observacoes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['oportunidade_item_id_relacionado'], ['opportunity_items.id'], name=op.f('opportunity_installation_item_oportunidade_item_id_relacio_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('opportunity_installation_items_opportunity_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_servico_id'], ['products.id'], name=op.f('opportunity_installation_items_produto_servico_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('opportunity_installation_items_pkey'))
    )
    op.create_table('opportunity_items',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('opportunity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('descricao_manual', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('produto_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('tipo_item', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('quantidade', sa.NUMERIC(precision=15, scale=4), autoincrement=False, nullable=True),
    sa.Column('unidade', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('valor_venda_unitario', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('observacoes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('opportunity_items_opportunity_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_id'], ['products.id'], name=op.f('opportunity_items_produto_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('opportunity_items_pkey'))
    )
    op.create_table('opportunity_parameters_sales',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('opportunity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('mkp_padrao', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('percentual_despesas_administrativas', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('percentual_comissao_padrao', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('pis_percentual', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('cofins_percentual', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('csll_percentual', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('irpj_percentual', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('iss_percentual', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('opportunity_parameters_sales_opportunity_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('opportunity_parameters_sales_pkey')),
    sa.UniqueConstraint('opportunity_id', name=op.f('opportunity_parameters_sales_opportunity_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('opportunity_budgets',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('opportunity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tipo_orcamento', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('fornecedor_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('data_orcamento', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('numero_orcamento', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('nome_vendedor', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('arquivo_original', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('origem_lancamento', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('nome_fornecedor_manual', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cnpj_fornecedor', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('moeda', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('cambio', sa.NUMERIC(precision=15, scale=6), autoincrement=False, nullable=True),
    sa.Column('data_cotacao', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('valor_total_itens', sa.NUMERIC(precision=18, scale=6), autoincrement=False, nullable=True),
    sa.Column('valor_total_impostos', sa.NUMERIC(precision=18, scale=6), autoincrement=False, nullable=True),
    sa.Column('valor_total_orcamento', sa.NUMERIC(precision=18, scale=6), autoincrement=False, nullable=True),
    sa.Column('aliquota_orcamento', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('criar_cenario_difal', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['suppliers.id'], name=op.f('opportunity_budgets_fornecedor_id_fkey')),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('opportunity_budgets_opportunity_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('opportunity_budgets_pkey'))
    )
    # ### end Alembic commands ###
