"""Add missing fields to RentalBudgetItem

Revision ID: b2243c882153
Revises: d9d66c413f1d
Create Date: 2026-05-18 16:32:06.684474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2243c882153'
down_revision: Union[str, Sequence[str], None] = 'd9d66c413f1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental_budget_items', sa.Column('kit_faturamento_separado', sa.Boolean(), nullable=True))
    op.add_column('rental_budget_items', sa.Column('kit_perc_comissao', sa.Numeric(precision=6, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rental_budget_items', 'kit_perc_comissao')
    op.drop_column('rental_budget_items', 'kit_faturamento_separado')
    # ### end Alembic commands ###
