"""add icms_abatido_unit to sales budget items

Revision ID: b34e697633b3
Revises: 2bfbfec6daf7
Create Date: 2026-04-23 15:20:28.020601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b34e697633b3'
down_revision: Union[str, Sequence[str], None] = '2bfbfec6daf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company_commercial_policies', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.add_column('sales_budget_items', sa.Column('icms_abatido_unit', sa.Numeric(precision=15, scale=4), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_budget_items', 'icms_abatido_unit')
    op.alter_column('company_commercial_policies', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
