"""Add opportunity_kit_id to RentalBudgetItem

Revision ID: bc5f48d08153
Revises: c54409ea23dc
Create Date: 2026-03-18 17:32:13.964004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc5f48d08153'
down_revision: Union[str, Sequence[str], None] = 'c54409ea23dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental_budget_items', sa.Column('opportunity_kit_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_rental_budget_items_opportunity_kit_id'), 'rental_budget_items', ['opportunity_kit_id'], unique=False)
    op.create_foreign_key(None, 'rental_budget_items', 'opportunity_kits', ['opportunity_kit_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rental_budget_items', type_='foreignkey')
    op.drop_index(op.f('ix_rental_budget_items_opportunity_kit_id'), table_name='rental_budget_items')
    op.drop_column('rental_budget_items', 'opportunity_kit_id')
    # ### end Alembic commands ###
