"""add_unidade_to_own_service

Revision ID: c3d491799897
Revises: b1c2d3fator01
Create Date: 2026-04-01 15:41:32.727620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3d491799897'
down_revision: Union[str, Sequence[str], None] = 'b1c2d3fator01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_man_hours_company_id'), table_name='man_hours')
    op.drop_index(op.f('ix_man_hours_tenant_id'), table_name='man_hours')
    op.add_column('own_services', sa.Column('unidade', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('own_services', 'unidade')
    op.create_index(op.f('ix_man_hours_tenant_id'), 'man_hours', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_man_hours_company_id'), 'man_hours', ['company_id'], unique=False)
    # ### end Alembic commands ###
