"""Add vlr_referencia_difal to products

Revision ID: c54409ea23dc
Revises: 99fb3a0d1201
Create Date: 2026-03-18 16:01:26.670726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c54409ea23dc'
down_revision: Union[str, Sequence[str], None] = '99fb3a0d1201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('vlr_referencia_difal', sa.Numeric(precision=18, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'vlr_referencia_difal')
    # ### end Alembic commands ###
