"""add fator_margem_servicos_produtos

Revision ID: c6c5280c35f2
Revises: 3c1be10427dc
Create Date: 2026-03-24 14:42:08.432416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6c5280c35f2'
down_revision: Union[str, Sequence[str], None] = '3c1be10427dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunity_kits', sa.Column('fator_margem_servicos_produtos', sa.Numeric(precision=10, scale=4), nullable=False, server_default='1.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunity_kits', 'fator_margem_servicos_produtos')
    # ### end Alembic commands ###
