"""add_company_id_to_customers_and_suppliers

Revision ID: c8f5ba3f5ad2
Revises: abc123def456
Create Date: 2026-04-17 18:47:57.773210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8f5ba3f5ad2'
down_revision: Union[str, Sequence[str], None] = 'abc123def456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_customers_company_id'), 'customers', ['company_id'], unique=False)
    op.create_foreign_key(None, 'customers', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.add_column('suppliers', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_suppliers_company_id'), 'suppliers', ['company_id'], unique=False)
    op.create_foreign_key(None, 'suppliers', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.drop_index(op.f('ix_suppliers_company_id'), table_name='suppliers')
    op.drop_column('suppliers', 'company_id')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_index(op.f('ix_customers_company_id'), table_name='customers')
    op.drop_column('customers', 'company_id')
    # ### end Alembic commands ###
