"""add_own_service_to_kit_costs

Revision ID: cd14b0761cd9
Revises: 5049a9581ee9
Create Date: 2026-03-31 14:40:03.512358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd14b0761cd9'
down_revision: Union[str, Sequence[str], None] = '5049a9581ee9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunity_kit_costs', sa.Column('tipo_item', sa.String(length=50), server_default='PRODUTO', nullable=False))
    op.add_column('opportunity_kit_costs', sa.Column('forma_execucao', sa.String(length=50), nullable=True))
    op.add_column('opportunity_kit_costs', sa.Column('own_service_id', sa.UUID(), nullable=True))
    op.alter_column('opportunity_kit_costs', 'product_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_opportunity_kit_costs_own_service_id'), 'opportunity_kit_costs', ['own_service_id'], unique=False)
    op.create_foreign_key(None, 'opportunity_kit_costs', 'own_services', ['own_service_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_own_service_items_service_id'), table_name='own_service_items')
    op.create_index(op.f('ix_own_service_items_own_service_id'), 'own_service_items', ['own_service_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_own_service_items_own_service_id'), table_name='own_service_items')
    op.create_index(op.f('ix_own_service_items_service_id'), 'own_service_items', ['own_service_id'], unique=False)
    op.drop_constraint(None, 'opportunity_kit_costs', type_='foreignkey')
    op.drop_index(op.f('ix_opportunity_kit_costs_own_service_id'), table_name='opportunity_kit_costs')
    op.alter_column('opportunity_kit_costs', 'product_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('opportunity_kit_costs', 'own_service_id')
    op.drop_column('opportunity_kit_costs', 'forma_execucao')
    op.drop_column('opportunity_kit_costs', 'tipo_item')
    op.create_index(op.f('ix_man_hours_tenant_id'), 'man_hours', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_man_hours_company_id'), 'man_hours', ['company_id'], unique=False)
    # ### end Alembic commands ###
