"""add_document_templates_module

Revision ID: d63873eee5e3
Revises: 084c0976a56c
Create Date: 2026-05-31 15:15:29.693492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd63873eee5e3'
down_revision: Union[str, Sequence[str], None] = '084c0976a56c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documento_modelo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('tipo_documento', sa.String(length=100), nullable=False),
    sa.Column('modulo_origem', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('conteudo_html', sa.Text(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documento_modelo_company_id'), 'documento_modelo', ['company_id'], unique=False)
    op.create_index(op.f('ix_documento_modelo_tenant_id'), 'documento_modelo', ['tenant_id'], unique=False)
    op.create_table('documento_auditoria',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('modelo_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.String(), nullable=False),
    sa.Column('acao', sa.String(length=100), nullable=False),
    sa.Column('data_hora', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['modelo_id'], ['documento_modelo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documento_auditoria_modelo_id'), 'documento_auditoria', ['modelo_id'], unique=False)
    op.create_index(op.f('ix_documento_auditoria_usuario_id'), 'documento_auditoria', ['usuario_id'], unique=False)
    op.create_table('documento_variavel',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('modelo_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('origem', sa.String(length=100), nullable=False),
    sa.Column('campo', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('obrigatoria', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['modelo_id'], ['documento_modelo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documento_variavel_modelo_id'), 'documento_variavel', ['modelo_id'], unique=False)
    op.create_table('documento_versao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('modelo_id', sa.UUID(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('conteudo_html', sa.Text(), nullable=False),
    sa.Column('usuario_id', sa.String(), nullable=False),
    sa.Column('data_publicacao', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['modelo_id'], ['documento_modelo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documento_versao_modelo_id'), 'documento_versao', ['modelo_id'], unique=False)
    op.create_index(op.f('ix_documento_versao_usuario_id'), 'documento_versao', ['usuario_id'], unique=False)
    op.alter_column('opportunity_kits', 'considerar_st_ou_difal',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'DIFAL'::character varying"))
    op.create_index(op.f('ix_sales_budget_approvals_sales_budget_id'), 'sales_budget_approvals', ['sales_budget_id'], unique=False)
    op.create_index(op.f('ix_sales_budget_approvals_usuario_aprovador_id'), 'sales_budget_approvals', ['usuario_aprovador_id'], unique=False)
    op.create_index(op.f('ix_sales_budget_history_sales_budget_id'), 'sales_budget_history', ['sales_budget_id'], unique=False)
    op.create_index(op.f('ix_sales_budget_history_usuario_id'), 'sales_budget_history', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_budget_history_usuario_id'), table_name='sales_budget_history')
    op.drop_index(op.f('ix_sales_budget_history_sales_budget_id'), table_name='sales_budget_history')
    op.drop_index(op.f('ix_sales_budget_approvals_usuario_aprovador_id'), table_name='sales_budget_approvals')
    op.drop_index(op.f('ix_sales_budget_approvals_sales_budget_id'), table_name='sales_budget_approvals')
    op.alter_column('opportunity_kits', 'considerar_st_ou_difal',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'DIFAL'::character varying"))
    op.drop_index(op.f('ix_documento_versao_usuario_id'), table_name='documento_versao')
    op.drop_index(op.f('ix_documento_versao_modelo_id'), table_name='documento_versao')
    op.drop_table('documento_versao')
    op.drop_index(op.f('ix_documento_variavel_modelo_id'), table_name='documento_variavel')
    op.drop_table('documento_variavel')
    op.drop_index(op.f('ix_documento_auditoria_usuario_id'), table_name='documento_auditoria')
    op.drop_index(op.f('ix_documento_auditoria_modelo_id'), table_name='documento_auditoria')
    op.drop_table('documento_auditoria')
    op.drop_index(op.f('ix_documento_modelo_tenant_id'), table_name='documento_modelo')
    op.drop_index(op.f('ix_documento_modelo_company_id'), table_name='documento_modelo')
    op.drop_table('documento_modelo')
    # ### end Alembic commands ###
