"""add_ncm_st_tables

Revision ID: d7369e8e6267
Revises: 62e2752266b9
Create Date: 2026-03-08 03:28:05.203985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7369e8e6267'
down_revision: Union[str, Sequence[str], None] = '62e2752266b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cad_ncm_st',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('state_id', sa.String(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cad_ncm_st_state_id'), 'cad_ncm_st', ['state_id'], unique=False)
    op.create_index(op.f('ix_cad_ncm_st_tenant_id'), 'cad_ncm_st', ['tenant_id'], unique=False)
    op.create_index('ix_cad_ncm_st_uf_desc', 'cad_ncm_st', ['state_id', 'description'], unique=False)
    op.create_table('cad_ncm_st_item',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cad_ncm_st_id', sa.String(), nullable=False),
    sa.Column('item', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('ncm_sh', sa.String(length=20), nullable=True),
    sa.Column('ncm_normalizado', sa.String(length=20), nullable=True),
    sa.Column('cest', sa.String(length=20), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('observacoes', sa.String(), nullable=True),
    sa.Column('vigencia_inicio', sa.DateTime(), nullable=True),
    sa.Column('fundamento', sa.String(), nullable=True),
    sa.Column('segmento_anexo', sa.String(length=255), nullable=True),
    sa.Column('cest_normalizado', sa.String(length=20), nullable=True),
    sa.Column('mva_percent', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('vigencia_fim', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cad_ncm_st_id'], ['cad_ncm_st.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cad_ncm_st_item_cad_ncm_st_id'), 'cad_ncm_st_item', ['cad_ncm_st_id'], unique=False)
    op.create_index(op.f('ix_cad_ncm_st_item_cest_normalizado'), 'cad_ncm_st_item', ['cest_normalizado'], unique=False)
    op.create_index(op.f('ix_cad_ncm_st_item_ncm_normalizado'), 'cad_ncm_st_item', ['ncm_normalizado'], unique=False)
    op.create_index(op.f('ix_cad_ncm_st_item_vigencia_fim'), 'cad_ncm_st_item', ['vigencia_fim'], unique=False)
    op.create_index(op.f('ix_cad_ncm_st_item_vigencia_inicio'), 'cad_ncm_st_item', ['vigencia_inicio'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cad_ncm_st_item_vigencia_inicio'), table_name='cad_ncm_st_item')
    op.drop_index(op.f('ix_cad_ncm_st_item_vigencia_fim'), table_name='cad_ncm_st_item')
    op.drop_index(op.f('ix_cad_ncm_st_item_ncm_normalizado'), table_name='cad_ncm_st_item')
    op.drop_index(op.f('ix_cad_ncm_st_item_cest_normalizado'), table_name='cad_ncm_st_item')
    op.drop_index(op.f('ix_cad_ncm_st_item_cad_ncm_st_id'), table_name='cad_ncm_st_item')
    op.drop_table('cad_ncm_st_item')
    op.drop_index('ix_cad_ncm_st_uf_desc', table_name='cad_ncm_st')
    op.drop_index(op.f('ix_cad_ncm_st_tenant_id'), table_name='cad_ncm_st')
    op.drop_index(op.f('ix_cad_ncm_st_state_id'), table_name='cad_ncm_st')
    op.drop_table('cad_ncm_st')
    # ### end Alembic commands ###
