"""Add rental item detailed kit snapshot fields

Revision ID: d9d66c413f1d
Revises: b34e697633b3
Create Date: 2026-04-24 17:27:01.891619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9d66c413f1d'
down_revision: Union[str, Sequence[str], None] = 'b34e697633b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental_budget_items', sa.Column('kit_investimento_total', sa.Numeric(precision=15, scale=4), nullable=True))
    op.add_column('rental_budget_items', sa.Column('kit_comissao', sa.Numeric(precision=15, scale=4), nullable=True))
    op.add_column('rental_budget_items', sa.Column('kit_vlr_instal_calc', sa.Numeric(precision=15, scale=4), nullable=True))
    op.add_column('rental_budget_items', sa.Column('kit_parcela_locacao', sa.Numeric(precision=15, scale=4), nullable=True))
    op.add_column('rental_budget_items', sa.Column('kit_venda_unit_monitoramento', sa.Numeric(precision=15, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rental_budget_items', 'kit_venda_unit_monitoramento')
    op.drop_column('rental_budget_items', 'kit_parcela_locacao')
    op.drop_column('rental_budget_items', 'kit_vlr_instal_calc')
    op.drop_column('rental_budget_items', 'kit_comissao')
    op.drop_column('rental_budget_items', 'kit_investimento_total')
    # ### end Alembic commands ###
