"""add sales proposals

Revision ID: dca8db58ff4e
Revises: 158c82263f5e
Create Date: 2026-04-06 12:48:08.571420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dca8db58ff4e'
down_revision: Union[str, Sequence[str], None] = '158c82263f5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_proposals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('vendedor_id', sa.String(), nullable=True),
    sa.Column('responsavel_id', sa.String(), nullable=True),
    sa.Column('numero_sequencial', sa.Integer(), nullable=False),
    sa.Column('numero_proposta', sa.String(length=50), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('fator_margem_produtos', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('fator_margem_servicos', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('fator_margem_instalacao', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('fator_margem_manutencao', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('frete_venda', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('despesas_adm', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('comissao', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responsavel_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendedor_id'], ['professionals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_proposals_company_id'), 'sales_proposals', ['company_id'], unique=False)
    op.create_index(op.f('ix_sales_proposals_customer_id'), 'sales_proposals', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sales_proposals_numero_proposta'), 'sales_proposals', ['numero_proposta'], unique=True)
    op.create_index(op.f('ix_sales_proposals_responsavel_id'), 'sales_proposals', ['responsavel_id'], unique=False)
    op.create_index(op.f('ix_sales_proposals_tenant_id'), 'sales_proposals', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_sales_proposals_vendedor_id'), 'sales_proposals', ['vendedor_id'], unique=False)
    op.create_table('sales_proposal_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('proposal_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('acao', sa.String(length=100), nullable=False),
    sa.Column('detalhes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['sales_proposals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_proposal_logs_proposal_id'), 'sales_proposal_logs', ['proposal_id'], unique=False)
    op.create_index(op.f('ix_sales_proposal_logs_user_id'), 'sales_proposal_logs', ['user_id'], unique=False)
    op.create_table('sales_proposal_kits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('proposal_id', sa.UUID(), nullable=False),
    sa.Column('opportunity_kit_id', sa.UUID(), nullable=False),
    sa.Column('quantidade_override', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_kit_id'], ['opportunity_kits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposal_id'], ['sales_proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_proposal_kits_opportunity_kit_id'), 'sales_proposal_kits', ['opportunity_kit_id'], unique=False)
    op.create_index(op.f('ix_sales_proposal_kits_proposal_id'), 'sales_proposal_kits', ['proposal_id'], unique=False)
    op.add_column('opportunity_kits', sa.Column('sales_proposal_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_opportunity_kits_sales_proposal_id'), 'opportunity_kits', ['sales_proposal_id'], unique=False)
    op.create_foreign_key(None, 'opportunity_kits', 'sales_proposals', ['sales_proposal_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'opportunity_kits', type_='foreignkey')
    op.drop_index(op.f('ix_opportunity_kits_sales_proposal_id'), table_name='opportunity_kits')
    op.drop_column('opportunity_kits', 'sales_proposal_id')
    op.drop_index(op.f('ix_sales_proposal_kits_proposal_id'), table_name='sales_proposal_kits')
    op.drop_index(op.f('ix_sales_proposal_kits_opportunity_kit_id'), table_name='sales_proposal_kits')
    op.drop_table('sales_proposal_kits')
    op.drop_index(op.f('ix_sales_proposal_logs_user_id'), table_name='sales_proposal_logs')
    op.drop_index(op.f('ix_sales_proposal_logs_proposal_id'), table_name='sales_proposal_logs')
    op.drop_table('sales_proposal_logs')
    op.drop_index(op.f('ix_sales_proposals_vendedor_id'), table_name='sales_proposals')
    op.drop_index(op.f('ix_sales_proposals_tenant_id'), table_name='sales_proposals')
    op.drop_index(op.f('ix_sales_proposals_responsavel_id'), table_name='sales_proposals')
    op.drop_index(op.f('ix_sales_proposals_numero_proposta'), table_name='sales_proposals')
    op.drop_index(op.f('ix_sales_proposals_customer_id'), table_name='sales_proposals')
    op.drop_index(op.f('ix_sales_proposals_company_id'), table_name='sales_proposals')
    op.drop_table('sales_proposals')
    # ### end Alembic commands ###
