"""Add CMT Module Tables

Revision ID: e51788359802
Revises: cb4e38fdedfc
Create Date: 2026-03-02 21:27:37.089431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e51788359802'
down_revision: Union[str, Sequence[str], None] = 'cb4e38fdedfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('municipalities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ibge_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_municipalities_ibge_code'), 'municipalities', ['ibge_code'], unique=True)
    op.create_index(op.f('ix_municipalities_name'), 'municipalities', ['name'], unique=False)
    op.create_index(op.f('ix_municipalities_state'), 'municipalities', ['state'], unique=False)
    op.create_table('cmt_source_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('municipality_id', sa.String(), nullable=False),
    sa.Column('document_name', sa.String(), nullable=False),
    sa.Column('document_type', sa.Enum('CTM', 'DECRETO', 'PORTARIA', 'OUTRO', name='cmtdocumenttype'), nullable=False),
    sa.Column('published_at', sa.Date(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('file_hash', sa.String(), nullable=True),
    sa.Column('version_label', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'ACTIVE', 'REPLACED', name='cmtdocumentstatus'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cmt_source_documents_municipality_id'), 'cmt_source_documents', ['municipality_id'], unique=False)
    op.create_index(op.f('ix_cmt_source_documents_tenant_id'), 'cmt_source_documents', ['tenant_id'], unique=False)
    op.create_table('cmt_import_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('municipality_id', sa.String(), nullable=True),
    sa.Column('source_document_id', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('rows_total', sa.Integer(), nullable=True),
    sa.Column('rows_inserted', sa.Integer(), nullable=True),
    sa.Column('rows_updated', sa.Integer(), nullable=True),
    sa.Column('rows_failed', sa.Integer(), nullable=True),
    sa.Column('warnings_count', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_document_id'], ['cmt_source_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cmt_import_logs_municipality_id'), 'cmt_import_logs', ['municipality_id'], unique=False)
    op.create_index(op.f('ix_cmt_import_logs_tenant_id'), 'cmt_import_logs', ['tenant_id'], unique=False)
    op.create_table('cmt_tax_codes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('municipality_id', sa.String(), nullable=False),
    sa.Column('source_document_id', sa.String(), nullable=True),
    sa.Column('municipal_code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('lc116_item', sa.String(), nullable=True),
    sa.Column('iss_rate', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('withheld_default', sa.Boolean(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'ACTIVE', 'REJECTED', name='cmtcodestatus'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['cmt_source_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cmt_tax_codes_municipality_id'), 'cmt_tax_codes', ['municipality_id'], unique=False)
    op.create_index(op.f('ix_cmt_tax_codes_source_document_id'), 'cmt_tax_codes', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_cmt_tax_codes_tenant_id'), 'cmt_tax_codes', ['tenant_id'], unique=False)
    op.create_table('cmt_service_mappings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('municipality_id', sa.String(), nullable=False),
    sa.Column('service_id', sa.String(), nullable=False),
    sa.Column('municipal_tax_code_id', sa.String(), nullable=False),
    sa.Column('iss_rate_override', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('withheld_override', sa.Boolean(), nullable=True),
    sa.Column('rule_priority', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['municipal_tax_code_id'], ['cmt_tax_codes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cmt_service_mappings_municipal_tax_code_id'), 'cmt_service_mappings', ['municipal_tax_code_id'], unique=False)
    op.create_index(op.f('ix_cmt_service_mappings_municipality_id'), 'cmt_service_mappings', ['municipality_id'], unique=False)
    op.create_index(op.f('ix_cmt_service_mappings_service_id'), 'cmt_service_mappings', ['service_id'], unique=False)
    op.create_index(op.f('ix_cmt_service_mappings_tenant_id'), 'cmt_service_mappings', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cmt_service_mappings_tenant_id'), table_name='cmt_service_mappings')
    op.drop_index(op.f('ix_cmt_service_mappings_service_id'), table_name='cmt_service_mappings')
    op.drop_index(op.f('ix_cmt_service_mappings_municipality_id'), table_name='cmt_service_mappings')
    op.drop_index(op.f('ix_cmt_service_mappings_municipal_tax_code_id'), table_name='cmt_service_mappings')
    op.drop_table('cmt_service_mappings')
    op.drop_index(op.f('ix_cmt_tax_codes_tenant_id'), table_name='cmt_tax_codes')
    op.drop_index(op.f('ix_cmt_tax_codes_source_document_id'), table_name='cmt_tax_codes')
    op.drop_index(op.f('ix_cmt_tax_codes_municipality_id'), table_name='cmt_tax_codes')
    op.drop_table('cmt_tax_codes')
    op.drop_index(op.f('ix_cmt_import_logs_tenant_id'), table_name='cmt_import_logs')
    op.drop_index(op.f('ix_cmt_import_logs_municipality_id'), table_name='cmt_import_logs')
    op.drop_table('cmt_import_logs')
    op.drop_index(op.f('ix_cmt_source_documents_tenant_id'), table_name='cmt_source_documents')
    op.drop_index(op.f('ix_cmt_source_documents_municipality_id'), table_name='cmt_source_documents')
    op.drop_table('cmt_source_documents')
    op.drop_index(op.f('ix_municipalities_state'), table_name='municipalities')
    op.drop_index(op.f('ix_municipalities_name'), table_name='municipalities')
    op.drop_index(op.f('ix_municipalities_ibge_code'), table_name='municipalities')
    op.drop_table('municipalities')
    # ### end Alembic commands ###
