"""Add opportunity module tables

Revision ID: e9845fcc62d9
Revises: 8d8bf5324cdb
Create Date: 2026-03-09 18:53:45.398224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9845fcc62d9'
down_revision: Union[str, Sequence[str], None] = '8d8bf5324cdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('numero_oportunidade', sa.String(length=50), nullable=False),
    sa.Column('titulo_oportunidade', sa.String(length=255), nullable=False),
    sa.Column('cliente_id', sa.String(), nullable=True),
    sa.Column('tipo_cliente', sa.String(length=20), nullable=True),
    sa.Column('tipo_operacao', sa.String(length=50), nullable=True),
    sa.Column('possui_instalacao', sa.Boolean(), nullable=True),
    sa.Column('possui_manutencao', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('data_abertura', sa.Date(), nullable=True),
    sa.Column('responsavel_comercial', sa.String(length=255), nullable=True),
    sa.Column('origem_oportunidade', sa.String(length=100), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('perfil_tributario_origem_id', sa.UUID(), nullable=False),
    sa.Column('valor_total_calculado', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('margem_estimada', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['perfil_tributario_origem_id'], ['company_tax_profiles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_oportunidade')
    )
    op.create_table('opportunity_budgets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('tipo_orcamento', sa.String(length=50), nullable=True),
    sa.Column('fornecedor_id', sa.String(), nullable=True),
    sa.Column('data_orcamento', sa.Date(), nullable=True),
    sa.Column('numero_orcamento', sa.String(length=100), nullable=True),
    sa.Column('nome_vendedor', sa.String(length=255), nullable=True),
    sa.Column('arquivo_original', sa.String(length=500), nullable=True),
    sa.Column('origem_lancamento', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunity_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('descricao_manual', sa.String(length=255), nullable=True),
    sa.Column('produto_id', sa.UUID(), nullable=True),
    sa.Column('tipo_item', sa.String(length=50), nullable=True),
    sa.Column('quantidade', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('unidade', sa.String(length=20), nullable=True),
    sa.Column('valor_venda_unitario', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunity_parameters_rent',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('prazo_contrato_meses', sa.Integer(), nullable=True),
    sa.Column('tipo_receita', sa.String(length=50), nullable=True),
    sa.Column('modo_precificacao', sa.String(length=50), nullable=True),
    sa.Column('margem_padrao_percentual', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('comissao_receita_liquida_percentual', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pis_percentual', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cofins_percentual', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('irpj_percentual', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('csll_percentual', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('iss_percentual', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fator_margem_locacao', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('taxa_juros_mensal_percentual', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('taxa_manutencao_anual_percentual', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id')
    )
    op.create_table('opportunity_parameters_sales',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('mkp_padrao', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('percentual_despesas_administrativas', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('percentual_comissao_padrao', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pis_percentual', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cofins_percentual', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('csll_percentual', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('irpj_percentual', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('iss_percentual', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id')
    )
    op.create_table('opportunity_budget_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('orcamento_id', sa.UUID(), nullable=False),
    sa.Column('codigo_fornecedor', sa.String(length=100), nullable=True),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('quantidade', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('unidade', sa.String(length=20), nullable=True),
    sa.Column('ncm', sa.String(length=10), nullable=True),
    sa.Column('ipi_percentual', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('icms_percentual', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('valor_unitario', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('produto_id', sa.UUID(), nullable=True),
    sa.Column('oportunidade_item_id_vinculado', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['oportunidade_item_id_vinculado'], ['opportunity_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['orcamento_id'], ['opportunity_budgets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunity_installation_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('oportunidade_item_id_relacionado', sa.UUID(), nullable=True),
    sa.Column('produto_servico_id', sa.UUID(), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('valor_unitario', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['oportunidade_item_id_relacionado'], ['opportunity_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_servico_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunity_items_kit',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_pai_id', sa.UUID(), nullable=False),
    sa.Column('produto_id', sa.UUID(), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['item_pai_id'], ['opportunity_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunity_maintenance_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('oportunidade_item_id_relacionado', sa.UUID(), nullable=True),
    sa.Column('produto_servico_id', sa.UUID(), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('valor_unitario', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['oportunidade_item_id_relacionado'], ['opportunity_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_servico_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opportunity_maintenance_items')
    op.drop_table('opportunity_items_kit')
    op.drop_table('opportunity_installation_items')
    op.drop_table('opportunity_budget_items')
    op.drop_table('opportunity_parameters_sales')
    op.drop_table('opportunity_parameters_rent')
    op.drop_table('opportunity_items')
    op.drop_table('opportunity_budgets')
    op.drop_table('opportunities')
    # ### end Alembic commands ###
