"""add_monitoring_fields

Revision ID: ef8b47e3c890
Revises: f04048b9429a
Create Date: 2026-06-18 12:07:02.232003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef8b47e3c890'
down_revision: Union[str, Sequence[str], None] = 'f04048b9429a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunity_kits', sa.Column('custo_monitoramento_unitario', sa.Numeric(precision=15, scale=4), nullable=False))
    op.add_column('opportunity_kits', sa.Column('fator_monitoramento', sa.Numeric(precision=10, scale=4), nullable=False))
    op.alter_column('sales_budget_items', 'perc_frete_venda',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=4),
               existing_nullable=False)
    op.alter_column('sales_budget_items', 'perc_pis',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=4),
               existing_nullable=False)
    op.alter_column('sales_budget_items', 'perc_cofins',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=4),
               existing_nullable=False)
    op.alter_column('sales_budget_items', 'perc_csll',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=4),
               existing_nullable=False)
    op.alter_column('sales_budget_items', 'perc_irpj',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=4),
               existing_nullable=False)
    op.alter_column('sales_budget_items', 'perc_icms',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=4),
               existing_nullable=False)
    op.alter_column('sales_budget_items', 'perc_iss',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=4),
               existing_nullable=False)
    op.alter_column('sales_budget_items', 'perc_despesa_adm',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=4),
               existing_nullable=False)
    op.alter_column('sales_budget_items', 'perc_comissao',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=4),
               existing_nullable=False)
    op.add_column('sales_budgets', sa.Column('prazo_contrato_meses', sa.Integer(), nullable=False))
    op.add_column('sales_budgets', sa.Column('prazo_instalacao_meses', sa.Integer(), nullable=False))
    op.add_column('sales_budgets', sa.Column('taxa_juros_mensal', sa.Numeric(precision=10, scale=6), nullable=False))
    op.add_column('sales_budgets', sa.Column('taxa_manutencao_anual', sa.Numeric(precision=6, scale=4), nullable=False))
    op.add_column('sales_budgets', sa.Column('tipo_receita_rental', sa.String(length=50), nullable=False))
    op.add_column('sales_budgets', sa.Column('fator_margem_padrao', sa.Numeric(precision=6, scale=4), nullable=False))
    op.add_column('sales_budgets', sa.Column('perc_instalacao_padrao', sa.Numeric(precision=6, scale=4), nullable=False))
    op.add_column('sales_budgets', sa.Column('perc_comissao_rental', sa.Numeric(precision=6, scale=4), nullable=False))
    op.add_column('sales_budgets', sa.Column('perc_pis_rental', sa.Numeric(precision=6, scale=4), nullable=False))
    op.add_column('sales_budgets', sa.Column('perc_cofins_rental', sa.Numeric(precision=6, scale=4), nullable=False))
    op.add_column('sales_budgets', sa.Column('perc_csll_rental', sa.Numeric(precision=6, scale=4), nullable=False))
    op.add_column('sales_budgets', sa.Column('perc_irpj_rental', sa.Numeric(precision=6, scale=4), nullable=False))
    op.add_column('sales_budgets', sa.Column('perc_iss_rental', sa.Numeric(precision=6, scale=4), nullable=False))
    op.alter_column('sales_budgets', 'perc_despesa_adm',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=4),
               existing_nullable=False)
    op.alter_column('sales_budgets', 'perc_comissao',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=4),
               existing_nullable=False)
    op.alter_column('sales_budgets', 'perc_frete_venda',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=4),
               existing_nullable=False)
    op.alter_column('sales_budgets', 'perc_pis',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=4),
               existing_nullable=False)
    op.alter_column('sales_budgets', 'perc_cofins',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=4),
               existing_nullable=False)
    op.alter_column('sales_budgets', 'perc_csll',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=4),
               existing_nullable=False)
    op.alter_column('sales_budgets', 'perc_irpj',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=4),
               existing_nullable=False)
    op.alter_column('sales_budgets', 'perc_iss',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=4),
               existing_nullable=False)
    op.alter_column('sales_budgets', 'perc_icms_interno',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=4),
               existing_nullable=False)
    op.alter_column('sales_budgets', 'perc_icms_externo',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=4),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales_budgets', 'perc_icms_externo',
               existing_type=sa.Numeric(precision=6, scale=4),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('sales_budgets', 'perc_icms_interno',
               existing_type=sa.Numeric(precision=6, scale=4),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('sales_budgets', 'perc_iss',
               existing_type=sa.Numeric(precision=6, scale=4),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('sales_budgets', 'perc_irpj',
               existing_type=sa.Numeric(precision=6, scale=4),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('sales_budgets', 'perc_csll',
               existing_type=sa.Numeric(precision=6, scale=4),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('sales_budgets', 'perc_cofins',
               existing_type=sa.Numeric(precision=6, scale=4),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('sales_budgets', 'perc_pis',
               existing_type=sa.Numeric(precision=6, scale=4),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('sales_budgets', 'perc_frete_venda',
               existing_type=sa.Numeric(precision=6, scale=4),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('sales_budgets', 'perc_comissao',
               existing_type=sa.Numeric(precision=6, scale=4),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('sales_budgets', 'perc_despesa_adm',
               existing_type=sa.Numeric(precision=6, scale=4),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.drop_column('sales_budgets', 'perc_iss_rental')
    op.drop_column('sales_budgets', 'perc_irpj_rental')
    op.drop_column('sales_budgets', 'perc_csll_rental')
    op.drop_column('sales_budgets', 'perc_cofins_rental')
    op.drop_column('sales_budgets', 'perc_pis_rental')
    op.drop_column('sales_budgets', 'perc_comissao_rental')
    op.drop_column('sales_budgets', 'perc_instalacao_padrao')
    op.drop_column('sales_budgets', 'fator_margem_padrao')
    op.drop_column('sales_budgets', 'tipo_receita_rental')
    op.drop_column('sales_budgets', 'taxa_manutencao_anual')
    op.drop_column('sales_budgets', 'taxa_juros_mensal')
    op.drop_column('sales_budgets', 'prazo_instalacao_meses')
    op.drop_column('sales_budgets', 'prazo_contrato_meses')
    op.alter_column('sales_budget_items', 'perc_comissao',
               existing_type=sa.Numeric(precision=6, scale=4),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('sales_budget_items', 'perc_despesa_adm',
               existing_type=sa.Numeric(precision=6, scale=4),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('sales_budget_items', 'perc_iss',
               existing_type=sa.Numeric(precision=6, scale=4),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('sales_budget_items', 'perc_icms',
               existing_type=sa.Numeric(precision=6, scale=4),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('sales_budget_items', 'perc_irpj',
               existing_type=sa.Numeric(precision=6, scale=4),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('sales_budget_items', 'perc_csll',
               existing_type=sa.Numeric(precision=6, scale=4),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('sales_budget_items', 'perc_cofins',
               existing_type=sa.Numeric(precision=6, scale=4),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('sales_budget_items', 'perc_pis',
               existing_type=sa.Numeric(precision=6, scale=4),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('sales_budget_items', 'perc_frete_venda',
               existing_type=sa.Numeric(precision=6, scale=4),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.drop_column('opportunity_kits', 'fator_monitoramento')
    op.drop_column('opportunity_kits', 'custo_monitoramento_unitario')
    # ### end Alembic commands ###
