"""add_licitacao_totals_and_status

Revision ID: f04048b9429a
Revises: 0c2984f83950
Create Date: 2026-06-18 13:22:02.156421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f04048b9429a'
down_revision: Union[str, Sequence[str], None] = '0c2984f83950'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('licitacao_items', sa.Column('custo_unitario', sa.Numeric(precision=15, scale=4), nullable=False, server_default='0.0'))
    op.add_column('licitacao_items', sa.Column('custo_total', sa.Numeric(precision=15, scale=4), nullable=False, server_default='0.0'))
    op.add_column('licitacao_items', sa.Column('venda_unitario', sa.Numeric(precision=15, scale=4), nullable=False, server_default='0.0'))
    op.add_column('licitacao_items', sa.Column('venda_total', sa.Numeric(precision=15, scale=4), nullable=False, server_default='0.0'))
    op.add_column('licitacao_items', sa.Column('lucro_estimado', sa.Numeric(precision=15, scale=4), nullable=False, server_default='0.0'))
    op.add_column('licitacao_items', sa.Column('margem_geral', sa.Numeric(precision=10, scale=4), nullable=False, server_default='0.0'))
    op.add_column('licitacao_lotes', sa.Column('custo_total', sa.Numeric(precision=15, scale=4), nullable=False, server_default='0.0'))
    op.add_column('licitacao_lotes', sa.Column('venda_total', sa.Numeric(precision=15, scale=4), nullable=False, server_default='0.0'))
    op.add_column('licitacao_lotes', sa.Column('lucro_estimado', sa.Numeric(precision=15, scale=4), nullable=False, server_default='0.0'))
    op.add_column('licitacao_lotes', sa.Column('margem_geral', sa.Numeric(precision=10, scale=4), nullable=False, server_default='0.0'))
    op.add_column('licitacoes', sa.Column('custo_total', sa.Numeric(precision=15, scale=4), nullable=False, server_default='0.0'))
    op.add_column('licitacoes', sa.Column('lucro_estimado', sa.Numeric(precision=15, scale=4), nullable=False, server_default='0.0'))
    op.add_column('licitacoes', sa.Column('totais_status', sa.String(length=50), nullable=False, server_default='PENDENTE_RECALCULO'))
    op.add_column('licitacoes', sa.Column('totais_atualizados_em', sa.DateTime(timezone=True), nullable=True))
    op.add_column('opportunity_kits', sa.Column('custo_total', sa.Numeric(precision=15, scale=4), nullable=False, server_default='0.0'))
    op.add_column('opportunity_kits', sa.Column('venda_total', sa.Numeric(precision=15, scale=4), nullable=False, server_default='0.0'))
    op.add_column('opportunity_kits', sa.Column('lucro_estimado', sa.Numeric(precision=15, scale=4), nullable=False, server_default='0.0'))
    op.add_column('opportunity_kits', sa.Column('margem_geral', sa.Numeric(precision=10, scale=4), nullable=False, server_default='0.0'))
    op.add_column('opportunity_kits', sa.Column('custo_unitario', sa.Numeric(precision=15, scale=4), nullable=False, server_default='0.0'))
    op.add_column('opportunity_kits', sa.Column('venda_unitario', sa.Numeric(precision=15, scale=4), nullable=False, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunity_kits', 'venda_unitario')
    op.drop_column('opportunity_kits', 'custo_unitario')
    op.drop_column('opportunity_kits', 'margem_geral')
    op.drop_column('opportunity_kits', 'lucro_estimado')
    op.drop_column('opportunity_kits', 'venda_total')
    op.drop_column('opportunity_kits', 'custo_total')
    op.drop_column('licitacoes', 'totais_atualizados_em')
    op.drop_column('licitacoes', 'totais_status')
    op.drop_column('licitacoes', 'lucro_estimado')
    op.drop_column('licitacoes', 'custo_total')
    op.drop_column('licitacao_lotes', 'margem_geral')
    op.drop_column('licitacao_lotes', 'lucro_estimado')
    op.drop_column('licitacao_lotes', 'venda_total')
    op.drop_column('licitacao_lotes', 'custo_total')
    op.drop_column('licitacao_items', 'margem_geral')
    op.drop_column('licitacao_items', 'lucro_estimado')
    op.drop_column('licitacao_items', 'venda_total')
    op.drop_column('licitacao_items', 'venda_unitario')
    op.drop_column('licitacao_items', 'custo_total')
    op.drop_column('licitacao_items', 'custo_unitario')
    # ### end Alembic commands ###
