"""remove_cmt_tables

Revision ID: f21ced20f061
Revises: 1b7070ba6588
Create Date: 2026-03-07 14:52:05.681511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f21ced20f061'
down_revision: Union[str, Sequence[str], None] = '1b7070ba6588'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('companies_municipality_id_fkey'), 'companies', type_='foreignkey')
    op.drop_constraint(op.f('companies_cmt_id_fkey'), 'companies', type_='foreignkey')
    op.create_foreign_key(None, 'companies', 'cities', ['municipality_id'], ['id'])
    op.drop_column('companies', 'cmt_id')

    op.drop_index(op.f('ix_cmt_service_mappings_municipal_tax_code_id'), table_name='cmt_service_mappings')
    op.drop_index(op.f('ix_cmt_service_mappings_municipality_id'), table_name='cmt_service_mappings')
    op.drop_index(op.f('ix_cmt_service_mappings_service_id'), table_name='cmt_service_mappings')
    op.drop_index(op.f('ix_cmt_service_mappings_tenant_id'), table_name='cmt_service_mappings')
    op.drop_table('cmt_service_mappings')

    op.drop_index(op.f('ix_cmt_import_logs_municipality_id'), table_name='cmt_import_logs')
    op.drop_index(op.f('ix_cmt_import_logs_tenant_id'), table_name='cmt_import_logs')
    op.drop_table('cmt_import_logs')

    op.drop_table('municipal_service_tax_rules')
    
    op.drop_index(op.f('ix_cmt_tax_codes_municipality_id'), table_name='cmt_tax_codes')
    op.drop_index(op.f('ix_cmt_tax_codes_source_document_id'), table_name='cmt_tax_codes')
    op.drop_index(op.f('ix_cmt_tax_codes_tenant_id'), table_name='cmt_tax_codes')
    op.drop_table('cmt_tax_codes')

    op.drop_index(op.f('ix_cmt_source_documents_municipality_id'), table_name='cmt_source_documents')
    op.drop_index(op.f('ix_cmt_source_documents_tenant_id'), table_name='cmt_source_documents')
    op.drop_table('cmt_source_documents')

    op.drop_table('municipal_source_documents')

    op.drop_index(op.f('ix_municipalities_ibge_code'), table_name='municipalities')
    op.drop_index(op.f('ix_municipalities_name'), table_name='municipalities')
    op.drop_index(op.f('ix_municipalities_state'), table_name='municipalities')
    op.drop_table('municipalities')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('cmt_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.create_foreign_key(op.f('companies_cmt_id_fkey'), 'companies', 'municipal_source_documents', ['cmt_id'], ['id'])
    op.create_foreign_key(op.f('companies_municipality_id_fkey'), 'companies', 'municipalities', ['municipality_id'], ['id'])
    op.create_table('municipalities',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ibge_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('municipalities_pkey'))
    )
    op.create_index(op.f('ix_municipalities_state'), 'municipalities', ['state'], unique=False)
    op.create_index(op.f('ix_municipalities_name'), 'municipalities', ['name'], unique=False)
    op.create_index(op.f('ix_municipalities_ibge_code'), 'municipalities', ['ibge_code'], unique=True)
    op.create_table('cmt_source_documents',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('municipality_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('document_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('document_type', postgresql.ENUM('CTM', 'DECRETO', 'PORTARIA', 'OUTRO', name='cmtdocumenttype'), autoincrement=False, nullable=False),
    sa.Column('published_at', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('valid_from', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('valid_to', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('file_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('version_label', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('DRAFT', 'APPROVED', 'ACTIVE', 'REPLACED', name='cmtdocumentstatus'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('cmt_source_documents_created_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], name=op.f('cmt_source_documents_municipality_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('cmt_source_documents_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('cmt_source_documents_pkey'))
    )
    op.create_index(op.f('ix_cmt_source_documents_tenant_id'), 'cmt_source_documents', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_cmt_source_documents_municipality_id'), 'cmt_source_documents', ['municipality_id'], unique=False)
    op.create_table('municipal_source_documents',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('municipality_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('document_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('valid_from', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('valid_to', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('file_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('municipal_source_documents_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('municipal_source_documents_pkey'))
    )
    op.create_table('cmt_import_logs',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('municipality_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source_document_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('rows_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rows_inserted', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rows_updated', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rows_failed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('warnings_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('cmt_import_logs_created_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], name=op.f('cmt_import_logs_municipality_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_document_id'], ['cmt_source_documents.id'], name=op.f('cmt_import_logs_source_document_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('cmt_import_logs_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('cmt_import_logs_pkey'))
    )
    op.create_index(op.f('ix_cmt_import_logs_tenant_id'), 'cmt_import_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_cmt_import_logs_municipality_id'), 'cmt_import_logs', ['municipality_id'], unique=False)
    op.create_table('cmt_service_mappings',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('municipality_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('service_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('municipal_tax_code_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('iss_rate_override', sa.NUMERIC(precision=9, scale=6), autoincrement=False, nullable=True),
    sa.Column('withheld_override', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('rule_priority', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('cmt_service_mappings_created_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['municipal_tax_code_id'], ['cmt_tax_codes.id'], name=op.f('cmt_service_mappings_municipal_tax_code_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], name=op.f('cmt_service_mappings_municipality_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('cmt_service_mappings_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('cmt_service_mappings_pkey'))
    )
    op.create_index(op.f('ix_cmt_service_mappings_tenant_id'), 'cmt_service_mappings', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_cmt_service_mappings_service_id'), 'cmt_service_mappings', ['service_id'], unique=False)
    op.create_index(op.f('ix_cmt_service_mappings_municipality_id'), 'cmt_service_mappings', ['municipality_id'], unique=False)
    op.create_index(op.f('ix_cmt_service_mappings_municipal_tax_code_id'), 'cmt_service_mappings', ['municipal_tax_code_id'], unique=False)
    op.create_table('municipal_service_tax_rules',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('municipality_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('service_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lc116_item', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('iss_rate', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True),
    sa.Column('withheld_default', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('valid_from', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('valid_to', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('source_document_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['source_document_id'], ['municipal_source_documents.id'], name=op.f('municipal_service_tax_rules_source_document_id_fkey')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('municipal_service_tax_rules_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('municipal_service_tax_rules_pkey'))
    )
    op.create_table('cmt_tax_codes',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('municipality_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('source_document_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('municipal_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('lc116_item', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('iss_rate', sa.NUMERIC(precision=9, scale=6), autoincrement=False, nullable=False),
    sa.Column('withheld_default', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('valid_from', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('valid_to', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('DRAFT', 'APPROVED', 'ACTIVE', 'REJECTED', name='cmtcodestatus'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('cmt_tax_codes_created_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], name=op.f('cmt_tax_codes_municipality_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['cmt_source_documents.id'], name=op.f('cmt_tax_codes_source_document_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('cmt_tax_codes_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('cmt_tax_codes_pkey'))
    )
    op.create_index(op.f('ix_cmt_tax_codes_tenant_id'), 'cmt_tax_codes', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_cmt_tax_codes_source_document_id'), 'cmt_tax_codes', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_cmt_tax_codes_municipality_id'), 'cmt_tax_codes', ['municipality_id'], unique=False)
    # ### end Alembic commands ###
