"""create_products_table

Revision ID: fdf5f6537f48
Revises: fdc6e2d11c7e
Create Date: 2026-03-08 04:41:07.138191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdf5f6537f48'
down_revision: Union[str, Sequence[str], None] = 'fdc6e2d11c7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('finalidade', sa.String(length=20), nullable=False),
    sa.Column('unidade', sa.String(length=20), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('ncm_codigo', sa.String(length=20), nullable=True),
    sa.Column('cest_codigo', sa.String(length=20), nullable=True),
    sa.Column('cmt_codigo', sa.String(length=20), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_cest_codigo'), 'products', ['cest_codigo'], unique=False)
    op.create_index(op.f('ix_products_cmt_codigo'), 'products', ['cmt_codigo'], unique=False)
    op.create_index(op.f('ix_products_codigo'), 'products', ['codigo'], unique=False)
    op.create_index(op.f('ix_products_company_id'), 'products', ['company_id'], unique=False)
    op.create_index(op.f('ix_products_ncm_codigo'), 'products', ['ncm_codigo'], unique=False)
    op.create_index(op.f('ix_products_tenant_id'), 'products', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_tenant_id'), table_name='products')
    op.drop_index(op.f('ix_products_ncm_codigo'), table_name='products')
    op.drop_index(op.f('ix_products_company_id'), table_name='products')
    op.drop_index(op.f('ix_products_codigo'), table_name='products')
    op.drop_index(op.f('ix_products_cmt_codigo'), table_name='products')
    op.drop_index(op.f('ix_products_cest_codigo'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
