"""Add quantidade to purchase_budget_items

Revision ID: fe80a46b6099
Revises: 4d78633a646e
Create Date: 2026-03-16 09:41:38.918544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe80a46b6099'
down_revision: Union[str, Sequence[str], None] = '4d78633a646e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_budget_items', sa.Column('quantidade', sa.Numeric(precision=15, scale=4), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_budget_items', 'quantidade')
    # ### end Alembic commands ###
