"""Create functional_profiles table

Revision ID: ff3d5acfa853
Revises: 3d5acfa853fb
Create Date: 2026-03-23 15:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff3d5acfa853'
down_revision: Union[str, Sequence[str], None] = '3d5acfa853fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('functional_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('margin_factor_limit', sa.Float(), nullable=False),
    sa.Column('view_director_consolidation', sa.Boolean(), nullable=True),
    sa.Column('is_protected', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('functional_profiles')
    # ### end Alembic commands ###
